; Microsoft (R) C/C++ Optimizing Compiler Version 19.51.36252 for x64
; cl /nologo /c /O2 /std:c++20 /EHsc /W3 /Isrc\include /Isrc\include\tenvex /FA cg_mat.cpp
; Listing generated by Microsoft (R) Optimizing Compiler Version 19.51.36252.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?set@detail@tnvx@@YA?AT__m128@@MMMM@Z		; tnvx::detail::set
PUBLIC	?mul@detail@tnvx@@YA?AT__m128@@T3@0@Z		; tnvx::detail::mul
PUBLIC	?with_w@detail@tnvx@@YA?AT__m128@@T3@0@Z	; tnvx::detail::with_w
PUBLIC	?mat_from_quat@detail@tnvx@@YA?AUmf4@@T__m128@@@Z ; tnvx::detail::mat_from_quat
PUBLIC	??0vec4@tnvx@@QEAA@MMMM@Z			; tnvx::vec4::vec4
PUBLIC	??0vec4@tnvx@@QEAA@T__m128@@@Z			; tnvx::vec4::vec4
PUBLIC	?eval@vec4@tnvx@@QEBA?AT__m128@@XZ		; tnvx::vec4::eval
PUBLIC	?one@vec4@tnvx@@SA?AU12@XZ			; tnvx::vec4::one
PUBLIC	?unit_x@vec4@tnvx@@SA?AU12@XZ			; tnvx::vec4::unit_x
PUBLIC	?unit_y@vec4@tnvx@@SA?AU12@XZ			; tnvx::vec4::unit_y
PUBLIC	?unit_z@vec4@tnvx@@SA?AU12@XZ			; tnvx::vec4::unit_z
PUBLIC	?unit_w@vec4@tnvx@@SA?AU12@XZ			; tnvx::vec4::unit_w
PUBLIC	??$get_lane@$01@detail@tnvx@@YAMT__m128@@@Z	; tnvx::detail::get_lane<2>
PUBLIC	?eval@quat@tnvx@@QEBA?AT__m128@@XZ		; tnvx::quat::eval
PUBLIC	??0mat4@tnvx@@QEAA@MMMMMMMMMMMMMMMM@Z		; tnvx::mat4::mat4
PUBLIC	??0mat4@tnvx@@QEAA@Uvec4@1@000@Z		; tnvx::mat4::mat4
PUBLIC	??0mat4@tnvx@@QEAA@AEBUmf4@@@Z			; tnvx::mat4::mat4
PUBLIC	?identity@mat4@tnvx@@SA?AU12@XZ			; tnvx::mat4::identity
PUBLIC	?translation@mat4@tnvx@@SA?AU12@AEBUvec4@2@@Z	; tnvx::mat4::translation
PUBLIC	?scaling@mat4@tnvx@@SA?AU12@MMM@Z		; tnvx::mat4::scaling
PUBLIC	?scaling@mat4@tnvx@@SA?AU12@AEBUvec4@2@@Z	; tnvx::mat4::scaling
PUBLIC	?from_quat@mat4@tnvx@@SA?AU12@AEBUquat@2@@Z	; tnvx::mat4::from_quat
PUBLIC	?col@mat4@tnvx@@QEBA?AUvec4@2@H@Z		; tnvx::mat4::col
PUBLIC	?eval@mat4@tnvx@@QEBA?AUmf4@@XZ			; tnvx::mat4::eval
PUBLIC	??$with_w@Uvec4@tnvx@@U12@@tnvx@@YA?AU?$WithW@Uvec4@tnvx@@U12@@0@AEBUvec4@0@0@Z ; tnvx::with_w<tnvx::vec4,tnvx::vec4>
PUBLIC	??0?$WithW@Uvec4@tnvx@@U12@@tnvx@@QEAA@AEIBUvec4@1@0@Z ; tnvx::WithW<tnvx::vec4,tnvx::vec4>::WithW<tnvx::vec4,tnvx::vec4>
PUBLIC	?eval@?$WithW@Uvec4@tnvx@@U12@@tnvx@@QEBA?AT__m128@@XZ ; tnvx::WithW<tnvx::vec4,tnvx::vec4>::eval
PUBLIC	??$?0U?$WithW@Uvec4@tnvx@@U12@@tnvx@@@vec4@tnvx@@QEAA@AEBU?$WithW@Uvec4@tnvx@@U12@@1@@Z ; tnvx::vec4::vec4<tnvx::WithW<tnvx::vec4,tnvx::vec4> >
PUBLIC	??$hadamard@Uvec4@tnvx@@U12@@tnvx@@YA?AU?$Hadamard@Uvec4@tnvx@@U12@@0@AEBUvec4@0@0@Z ; tnvx::hadamard<tnvx::vec4,tnvx::vec4>
PUBLIC	??0?$Hadamard@Uvec4@tnvx@@U12@@tnvx@@QEAA@AEIBUvec4@1@0@Z ; tnvx::Hadamard<tnvx::vec4,tnvx::vec4>::Hadamard<tnvx::vec4,tnvx::vec4>
PUBLIC	?eval@?$Hadamard@Uvec4@tnvx@@U12@@tnvx@@QEBA?AT__m128@@XZ ; tnvx::Hadamard<tnvx::vec4,tnvx::vec4>::eval
PUBLIC	??$?0U?$Hadamard@Uvec4@tnvx@@U12@@tnvx@@@vec4@tnvx@@QEAA@AEBU?$Hadamard@Uvec4@tnvx@@U12@@1@@Z ; tnvx::vec4::vec4<tnvx::Hadamard<tnvx::vec4,tnvx::vec4> >
PUBLIC	cg_mat_from_quat
PUBLIC	cg_mat_translation
PUBLIC	cg_mat_scaling_vec
PUBLIC	cg_mat_scaling_scalar
PUBLIC	cg_mat_identity
PUBLIC	cg_mat_at
PUBLIC	??$at@$01$00@mat4@tnvx@@QEBAMXZ			; tnvx::mat4::at<2,1>
PUBLIC	cg_mat_col
PUBLIC	cg_mat_from_quat_value
PUBLIC	cg_mat_translation_value
PUBLIC	cg_mat_scaling_scalar_value
PUBLIC	cg_mat_identity_value
PUBLIC	__xmm@0000000000000000000000003f800000
PUBLIC	__xmm@00000000000000003f80000000000000
PUBLIC	__xmm@000000003f8000000000000000000000
PUBLIC	__xmm@000000003f8000003f8000003f800000
PUBLIC	__xmm@3f800000000000000000000000000000
PUBLIC	__xmm@3f8000003f8000003f8000003f800000
EXTRN	_fltused:DWORD
;	COMDAT pdata
pdata	SEGMENT
$pdata$?mat_from_quat@detail@tnvx@@YA?AUmf4@@T__m128@@@Z DD imagerel $LN10
	DD	imagerel $LN10+168
	DD	imagerel $unwind$?mat_from_quat@detail@tnvx@@YA?AUmf4@@T__m128@@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?from_quat@mat4@tnvx@@SA?AU12@AEBUquat@2@@Z DD imagerel $LN19
	DD	imagerel $LN19+168
	DD	imagerel $unwind$?from_quat@mat4@tnvx@@SA?AU12@AEBUquat@2@@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$cg_mat_from_quat DD imagerel $LN41
	DD	imagerel $LN41+52
	DD	imagerel $unwind$cg_mat_from_quat
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$cg_mat_from_quat DD imagerel $LN41+52
	DD	imagerel $LN41+702
	DD	imagerel $chain$0$cg_mat_from_quat
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$cg_mat_from_quat DD imagerel $LN41+702
	DD	imagerel $LN41+898
	DD	imagerel $chain$1$cg_mat_from_quat
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$cg_mat_translation DD imagerel $LN95
	DD	imagerel $LN95+55
	DD	imagerel $unwind$cg_mat_translation
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$cg_mat_translation DD imagerel $LN95+55
	DD	imagerel $LN95+263
	DD	imagerel $chain$0$cg_mat_translation
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$cg_mat_translation DD imagerel $LN95+263
	DD	imagerel $LN95+324
	DD	imagerel $chain$1$cg_mat_translation
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$cg_mat_scaling_vec DD imagerel $LN138
	DD	imagerel $LN138+56
	DD	imagerel $unwind$cg_mat_scaling_vec
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$cg_mat_scaling_vec DD imagerel $LN138+56
	DD	imagerel $LN138+322
	DD	imagerel $chain$0$cg_mat_scaling_vec
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$cg_mat_scaling_vec DD imagerel $LN138+322
	DD	imagerel $LN138+400
	DD	imagerel $chain$1$cg_mat_scaling_vec
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$cg_mat_scaling_scalar DD imagerel $LN39
	DD	imagerel $LN39+33
	DD	imagerel $unwind$cg_mat_scaling_scalar
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$cg_mat_scaling_scalar DD imagerel $LN39+33
	DD	imagerel $LN39+341
	DD	imagerel $chain$1$cg_mat_scaling_scalar
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$2$cg_mat_scaling_scalar DD imagerel $LN39+341
	DD	imagerel $LN39+425
	DD	imagerel $chain$2$cg_mat_scaling_scalar
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$cg_mat_from_quat_value DD imagerel $LN24
	DD	imagerel $LN24+168
	DD	imagerel $unwind$cg_mat_from_quat_value
pdata	ENDS
;	COMDAT __xmm@3f8000003f8000003f8000003f800000
CONST	SEGMENT
__xmm@3f8000003f8000003f8000003f800000 DB 00H, 00H, 080H, '?', 00H, 00H, 080H
	DB	'?', 00H, 00H, 080H, '?', 00H, 00H, 080H, '?'
CONST	ENDS
;	COMDAT __xmm@3f800000000000000000000000000000
CONST	SEGMENT
__xmm@3f800000000000000000000000000000 DB 00H, 00H, 00H, 00H, 00H, 00H, 00H
	DB	00H, 00H, 00H, 00H, 00H, 00H, 00H, 080H, '?'
CONST	ENDS
;	COMDAT __xmm@000000003f8000003f8000003f800000
CONST	SEGMENT
__xmm@000000003f8000003f8000003f800000 DB 00H, 00H, 080H, '?', 00H, 00H, 080H
	DB	'?', 00H, 00H, 080H, '?', 00H, 00H, 00H, 00H
CONST	ENDS
;	COMDAT __xmm@000000003f8000000000000000000000
CONST	SEGMENT
__xmm@000000003f8000000000000000000000 DB 00H, 00H, 00H, 00H, 00H, 00H, 00H
	DB	00H, 00H, 00H, 080H, '?', 00H, 00H, 00H, 00H
CONST	ENDS
;	COMDAT __xmm@00000000000000003f80000000000000
CONST	SEGMENT
__xmm@00000000000000003f80000000000000 DB 00H, 00H, 00H, 00H, 00H, 00H, 080H
	DB	'?', 00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H
CONST	ENDS
;	COMDAT __xmm@0000000000000000000000003f800000
CONST	SEGMENT
__xmm@0000000000000000000000003f800000 DB 00H, 00H, 080H, '?', 00H, 00H, 00H
	DB	00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$cg_mat_from_quat_value DD 030e01H
	DD	0680eH
	DD	02204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$2$cg_mat_scaling_scalar DD 021H
	DD	imagerel $LN39
	DD	imagerel $LN39+33
	DD	imagerel $unwind$cg_mat_scaling_scalar
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$1$cg_mat_scaling_scalar DD 040b21H
	DD	0740bH
	DD	023405H
	DD	imagerel $LN39
	DD	imagerel $LN39+33
	DD	imagerel $unwind$cg_mat_scaling_scalar
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$cg_mat_scaling_scalar DD 010401H
	DD	0204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$1$cg_mat_scaling_vec DD 021H
	DD	imagerel $LN138
	DD	imagerel $LN138+56
	DD	imagerel $unwind$cg_mat_scaling_vec
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$cg_mat_scaling_vec DD 020521H
	DD	023405H
	DD	imagerel $LN138
	DD	imagerel $LN138+56
	DD	imagerel $unwind$cg_mat_scaling_vec
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$cg_mat_scaling_vec DD 032601H
	DD	06826H
	DD	02204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$1$cg_mat_translation DD 021H
	DD	imagerel $LN95
	DD	imagerel $LN95+55
	DD	imagerel $unwind$cg_mat_translation
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$cg_mat_translation DD 020421H
	DD	03404H
	DD	imagerel $LN95
	DD	imagerel $LN95+55
	DD	imagerel $unwind$cg_mat_translation
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$cg_mat_translation DD 010401H
	DD	0204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$1$cg_mat_from_quat DD 021H
	DD	imagerel $LN41
	DD	imagerel $LN41+52
	DD	imagerel $unwind$cg_mat_from_quat
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$cg_mat_from_quat DD 020521H
	DD	063405H
	DD	imagerel $LN41
	DD	imagerel $LN41+52
	DD	imagerel $unwind$cg_mat_from_quat
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$cg_mat_from_quat DD 072101H
	DD	08821H
	DD	017811H
	DD	026809H
	DD	06204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?from_quat@mat4@tnvx@@SA?AU12@AEBUquat@2@@Z DD 030e01H
	DD	0680eH
	DD	02204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?mat_from_quat@detail@tnvx@@YA?AUmf4@@T__m128@@@Z DD 030e01H
	DD	0680eH
	DD	02204H
xdata	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?set@detail@tnvx@@YA?AT__m128@@MMMM@Z
_TEXT	SEGMENT
a$ = 8
b$ = 16
c$ = 24
d$ = 32
?set@detail@tnvx@@YA?AT__m128@@MMMM@Z PROC		; tnvx::detail::set, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	unpcklps xmm2, xmm3
	unpcklps xmm0, xmm1
	movlhps	xmm0, xmm2
; Line 24
	ret	0
?set@detail@tnvx@@YA?AT__m128@@MMMM@Z ENDP		; tnvx::detail::set
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?mul@detail@tnvx@@YA?AT__m128@@T3@0@Z
_TEXT	SEGMENT
l$ = 8
r$ = 16
?mul@detail@tnvx@@YA?AT__m128@@T3@0@Z PROC		; tnvx::detail::mul, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 103
	movups	xmm0, XMMWORD PTR [rcx]
	mulps	xmm0, XMMWORD PTR [rdx]
; Line 104
	ret	0
?mul@detail@tnvx@@YA?AT__m128@@T3@0@Z ENDP		; tnvx::detail::mul
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?with_w@detail@tnvx@@YA?AT__m128@@T3@0@Z
_TEXT	SEGMENT
xyz_source$ = 8
w_source$ = 16
?with_w@detail@tnvx@@YA?AT__m128@@T3@0@Z PROC		; tnvx::detail::with_w, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 232
	movups	xmm0, XMMWORD PTR [rcx]
	blendps	xmm0, XMMWORD PTR [rdx], 8
; Line 233
	ret	0
?with_w@detail@tnvx@@YA?AT__m128@@T3@0@Z ENDP		; tnvx::detail::with_w
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?mat_from_quat@detail@tnvx@@YA?AUmf4@@T__m128@@@Z
_TEXT	SEGMENT
__$ReturnAddress$ = 32
q$ = 40
?mat_from_quat@detail@tnvx@@YA?AUmf4@@T__m128@@@Z PROC	; tnvx::detail::mat_from_quat, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 286
$LN10:
	sub	rsp, 24
; Line 287
	movups	xmm5, XMMWORD PTR [rdx]
	xorps	xmm1, xmm1
	movaps	XMMWORD PTR [rsp], xmm6
	movaps	xmm3, xmm5
; Line 23
	movdqa	xmm6, XMMWORD PTR __xmm@000000003f8000003f8000003f800000
; Line 287
	addps	xmm3, xmm5
; Line 288
	movaps	xmm2, xmm5
; Line 296
	movaps	xmm4, xmm5
	shufps	xmm4, xmm5, 201				; 000000c9H
; Line 310
	mov	rax, rcx
	shufps	xmm5, xmm5, 255				; 000000ffH
	mulps	xmm2, xmm3
	mulps	xmm4, xmm3
	shufps	xmm3, xmm3, 210				; 000000d2H
	movaps	xmm0, xmm2
	mulps	xmm5, xmm3
	shufps	xmm0, xmm2, 193				; 000000c1H
	subps	xmm6, xmm0
	shufps	xmm2, xmm2, 218				; 000000daH
	subps	xmm6, xmm2
	movaps	xmm2, xmm5
	addps	xmm2, xmm4
	subps	xmm4, xmm5
	blendps	xmm6, xmm1, 8
	movaps	xmm0, xmm6
	shufps	xmm2, xmm2, 210				; 000000d2H
	movaps	xmm1, xmm6
	blendps	xmm0, xmm2, 2
	blendps	xmm0, xmm4, 4
	blendps	xmm6, xmm2, 1
	blendps	xmm6, xmm4, 2
	blendps	xmm1, xmm4, 1
	movups	XMMWORD PTR [rcx], xmm0
; Line 23
	movdqa	xmm0, XMMWORD PTR __xmm@3f800000000000000000000000000000
; Line 306
	blendps	xmm1, xmm2, 4
; Line 307
	movups	XMMWORD PTR [rcx+32], xmm6
; Line 311
	movaps	xmm6, XMMWORD PTR [rsp]
	movups	XMMWORD PTR [rcx+48], xmm0
	movups	XMMWORD PTR [rcx+16], xmm1
	add	rsp, 24
	ret	0
?mat_from_quat@detail@tnvx@@YA?AUmf4@@T__m128@@@Z ENDP	; tnvx::detail::mat_from_quat
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0vec4@tnvx@@QEAA@MMMM@Z
_TEXT	SEGMENT
this$ = 8
x$ = 16
y$ = 24
z$ = 32
w$ = 40
??0vec4@tnvx@@QEAA@MMMM@Z PROC				; tnvx::vec4::vec4, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\vec4_impl.hpp
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movss	xmm4, DWORD PTR w$[rsp]
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\vec4_impl.hpp
; Line 12
	mov	rax, rcx
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	unpcklps xmm3, xmm4
	unpcklps xmm1, xmm2
	movlhps	xmm1, xmm3
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\vec4_impl.hpp
; Line 10
	movups	XMMWORD PTR [rcx], xmm1
; Line 12
	ret	0
??0vec4@tnvx@@QEAA@MMMM@Z ENDP				; tnvx::vec4::vec4
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0vec4@tnvx@@QEAA@T__m128@@@Z
_TEXT	SEGMENT
this$ = 8
value$ = 16
??0vec4@tnvx@@QEAA@T__m128@@@Z PROC			; tnvx::vec4::vec4, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\vec4_impl.hpp
; Line 22
	movups	xmm0, XMMWORD PTR [rdx]
; Line 24
	mov	rax, rcx
	movups	XMMWORD PTR [rcx], xmm0
	ret	0
??0vec4@tnvx@@QEAA@T__m128@@@Z ENDP			; tnvx::vec4::vec4
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?eval@vec4@tnvx@@QEBA?AT__m128@@XZ
_TEXT	SEGMENT
this$ = 8
__$ReturnUdt$ = 16
?eval@vec4@tnvx@@QEBA?AT__m128@@XZ PROC			; tnvx::vec4::eval, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\vec4_impl.hpp
; Line 17
	movups	xmm0, XMMWORD PTR [rcx]
	mov	rax, rdx
	movups	XMMWORD PTR [rdx], xmm0
; Line 18
	ret	0
?eval@vec4@tnvx@@QEBA?AT__m128@@XZ ENDP			; tnvx::vec4::eval
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?one@vec4@tnvx@@SA?AU12@XZ
_TEXT	SEGMENT
__$ReturnUdt$ = 8
?one@vec4@tnvx@@SA?AU12@XZ PROC				; tnvx::vec4::one, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\vec4_impl.hpp
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movdqa	xmm0, XMMWORD PTR __xmm@3f8000003f8000003f8000003f800000
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\vec4_impl.hpp
; Line 33
	mov	rax, rcx
; Line 10
	movups	XMMWORD PTR [rcx], xmm0
; Line 34
	ret	0
?one@vec4@tnvx@@SA?AU12@XZ ENDP				; tnvx::vec4::one
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?unit_x@vec4@tnvx@@SA?AU12@XZ
_TEXT	SEGMENT
__$ReturnUdt$ = 8
?unit_x@vec4@tnvx@@SA?AU12@XZ PROC			; tnvx::vec4::unit_x, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\vec4_impl.hpp
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movdqa	xmm0, XMMWORD PTR __xmm@0000000000000000000000003f800000
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\vec4_impl.hpp
; Line 38
	mov	rax, rcx
; Line 10
	movups	XMMWORD PTR [rcx], xmm0
; Line 39
	ret	0
?unit_x@vec4@tnvx@@SA?AU12@XZ ENDP			; tnvx::vec4::unit_x
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?unit_y@vec4@tnvx@@SA?AU12@XZ
_TEXT	SEGMENT
__$ReturnUdt$ = 8
?unit_y@vec4@tnvx@@SA?AU12@XZ PROC			; tnvx::vec4::unit_y, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\vec4_impl.hpp
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movdqa	xmm0, XMMWORD PTR __xmm@00000000000000003f80000000000000
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\vec4_impl.hpp
; Line 43
	mov	rax, rcx
; Line 10
	movups	XMMWORD PTR [rcx], xmm0
; Line 44
	ret	0
?unit_y@vec4@tnvx@@SA?AU12@XZ ENDP			; tnvx::vec4::unit_y
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?unit_z@vec4@tnvx@@SA?AU12@XZ
_TEXT	SEGMENT
__$ReturnUdt$ = 8
?unit_z@vec4@tnvx@@SA?AU12@XZ PROC			; tnvx::vec4::unit_z, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\vec4_impl.hpp
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movdqa	xmm0, XMMWORD PTR __xmm@000000003f8000000000000000000000
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\vec4_impl.hpp
; Line 48
	mov	rax, rcx
; Line 10
	movups	XMMWORD PTR [rcx], xmm0
; Line 49
	ret	0
?unit_z@vec4@tnvx@@SA?AU12@XZ ENDP			; tnvx::vec4::unit_z
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?unit_w@vec4@tnvx@@SA?AU12@XZ
_TEXT	SEGMENT
__$ReturnUdt$ = 8
?unit_w@vec4@tnvx@@SA?AU12@XZ PROC			; tnvx::vec4::unit_w, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\vec4_impl.hpp
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movdqa	xmm0, XMMWORD PTR __xmm@3f800000000000000000000000000000
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\vec4_impl.hpp
; Line 53
	mov	rax, rcx
; Line 10
	movups	XMMWORD PTR [rcx], xmm0
; Line 54
	ret	0
?unit_w@vec4@tnvx@@SA?AU12@XZ ENDP			; tnvx::vec4::unit_w
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$get_lane@$01@detail@tnvx@@YAMT__m128@@@Z
_TEXT	SEGMENT
v$ = 8
??$get_lane@$01@detail@tnvx@@YAMT__m128@@@Z PROC	; tnvx::detail::get_lane<2>, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 73
	movss	xmm0, DWORD PTR [rcx+8]
; Line 75
	ret	0
??$get_lane@$01@detail@tnvx@@YAMT__m128@@@Z ENDP	; tnvx::detail::get_lane<2>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?eval@quat@tnvx@@QEBA?AT__m128@@XZ
_TEXT	SEGMENT
this$ = 8
__$ReturnUdt$ = 16
?eval@quat@tnvx@@QEBA?AT__m128@@XZ PROC			; tnvx::quat::eval, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\quat\quat_impl.hpp
; Line 32
	movups	xmm0, XMMWORD PTR [rcx]
	mov	rax, rdx
	movups	XMMWORD PTR [rdx], xmm0
; Line 33
	ret	0
?eval@quat@tnvx@@QEBA?AT__m128@@XZ ENDP			; tnvx::quat::eval
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0mat4@tnvx@@QEAA@MMMMMMMMMMMMMMMM@Z
_TEXT	SEGMENT
this$ = 8
m00$ = 16
m10$ = 24
m20$ = 32
m30$ = 40
m01$ = 48
m11$ = 56
m21$ = 64
m31$ = 72
m02$ = 80
m12$ = 88
m22$ = 96
m32$ = 104
m03$ = 112
m13$ = 120
m23$ = 128
m33$ = 136
??0mat4@tnvx@@QEAA@MMMMMMMMMMMMMMMM@Z PROC		; tnvx::mat4::mat4, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movss	xmm0, DWORD PTR m11$[rsp]
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; Line 21
	mov	rax, rcx
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movss	xmm4, DWORD PTR m30$[rsp]
	unpcklps xmm3, xmm4
	unpcklps xmm1, xmm2
	movss	xmm2, DWORD PTR m21$[rsp]
	movlhps	xmm1, xmm3
	movss	xmm3, DWORD PTR m01$[rsp]
	unpcklps xmm3, xmm0
	movss	xmm0, DWORD PTR m12$[rsp]
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; Line 16
	movups	XMMWORD PTR [rcx], xmm1
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movss	xmm1, DWORD PTR m31$[rsp]
	unpcklps xmm2, xmm1
	movss	xmm1, DWORD PTR m32$[rsp]
	movlhps	xmm3, xmm2
	movss	xmm2, DWORD PTR m22$[rsp]
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; Line 16
	movups	XMMWORD PTR [rcx+16], xmm3
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movss	xmm3, DWORD PTR m02$[rsp]
	unpcklps xmm3, xmm0
	movss	xmm0, DWORD PTR m13$[rsp]
	unpcklps xmm2, xmm1
	movss	xmm1, DWORD PTR m33$[rsp]
	movlhps	xmm3, xmm2
	movss	xmm2, DWORD PTR m23$[rsp]
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; Line 16
	movups	XMMWORD PTR [rcx+32], xmm3
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movss	xmm3, DWORD PTR m03$[rsp]
	unpcklps xmm3, xmm0
	unpcklps xmm2, xmm1
	movlhps	xmm3, xmm2
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; Line 16
	movups	XMMWORD PTR [rcx+48], xmm3
; Line 21
	ret	0
??0mat4@tnvx@@QEAA@MMMMMMMMMMMMMMMM@Z ENDP		; tnvx::mat4::mat4
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0mat4@tnvx@@QEAA@Uvec4@1@000@Z
_TEXT	SEGMENT
this$ = 8
col0$ = 16
col1$ = 24
col2$ = 32
col3$ = 40
??0mat4@tnvx@@QEAA@Uvec4@1@000@Z PROC			; tnvx::mat4::mat4, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; Line 38
	movups	xmm0, XMMWORD PTR [rdx]
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\vec4_impl.hpp
; Line 17
	movups	xmm2, XMMWORD PTR [r8]
	movups	xmm3, XMMWORD PTR [r9]
	mov	rax, QWORD PTR col3$[rsp]
	movups	xmm1, XMMWORD PTR [rax]
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; Line 40
	mov	rax, rcx
	movups	XMMWORD PTR [rcx], xmm0
	movups	XMMWORD PTR [rcx+16], xmm2
	movups	XMMWORD PTR [rcx+32], xmm3
	movups	XMMWORD PTR [rcx+48], xmm1
	ret	0
??0mat4@tnvx@@QEAA@Uvec4@1@000@Z ENDP			; tnvx::mat4::mat4
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0mat4@tnvx@@QEAA@AEBUmf4@@@Z
_TEXT	SEGMENT
this$ = 8
data$ = 16
??0mat4@tnvx@@QEAA@AEBUmf4@@@Z PROC			; tnvx::mat4::mat4, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; Line 62
	movaps	xmm0, XMMWORD PTR [rdx]
; Line 64
	mov	rax, rcx
	movups	XMMWORD PTR [rcx], xmm0
	movaps	xmm1, XMMWORD PTR [rdx+16]
	movups	XMMWORD PTR [rcx+16], xmm1
	movaps	xmm0, XMMWORD PTR [rdx+32]
	movups	XMMWORD PTR [rcx+32], xmm0
	movaps	xmm1, XMMWORD PTR [rdx+48]
	movups	XMMWORD PTR [rcx+48], xmm1
	ret	0
??0mat4@tnvx@@QEAA@AEBUmf4@@@Z ENDP			; tnvx::mat4::mat4
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?identity@mat4@tnvx@@SA?AU12@XZ
_TEXT	SEGMENT
__$ReturnUdt$ = 8
?identity@mat4@tnvx@@SA?AU12@XZ PROC			; tnvx::mat4::identity, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movdqa	xmm0, XMMWORD PTR __xmm@0000000000000000000000003f800000
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; Line 54
	mov	rax, rcx
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movdqa	xmm1, XMMWORD PTR __xmm@00000000000000003f80000000000000
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; Line 16
	movups	XMMWORD PTR [rcx], xmm0
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movdqa	xmm0, XMMWORD PTR __xmm@000000003f8000000000000000000000
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; Line 16
	movups	XMMWORD PTR [rcx+16], xmm1
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movdqa	xmm1, XMMWORD PTR __xmm@3f800000000000000000000000000000
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; Line 16
	movups	XMMWORD PTR [rcx+32], xmm0
	movups	XMMWORD PTR [rcx+48], xmm1
; Line 58
	ret	0
?identity@mat4@tnvx@@SA?AU12@XZ ENDP			; tnvx::mat4::identity
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?translation@mat4@tnvx@@SA?AU12@AEBUvec4@2@@Z
_TEXT	SEGMENT
__$ReturnUdt$ = 8
t$ = 16
?translation@mat4@tnvx@@SA?AU12@AEBUvec4@2@@Z PROC	; tnvx::mat4::translation, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\with_w_impl.hpp
; Line 11
	movups	xmm3, XMMWORD PTR [rdx]
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; Line 69
	mov	rax, rcx
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 232
	blendps	xmm3, XMMWORD PTR __xmm@3f8000003f8000003f8000003f800000, 8
; Line 23
	movdqa	xmm2, XMMWORD PTR __xmm@000000003f8000000000000000000000
	movdqa	xmm1, XMMWORD PTR __xmm@00000000000000003f80000000000000
	movdqa	xmm0, XMMWORD PTR __xmm@0000000000000000000000003f800000
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; Line 38
	movups	XMMWORD PTR [rcx+48], xmm3
	movups	XMMWORD PTR [rcx], xmm0
	movups	XMMWORD PTR [rcx+16], xmm1
	movups	XMMWORD PTR [rcx+32], xmm2
; Line 70
	ret	0
?translation@mat4@tnvx@@SA?AU12@AEBUvec4@2@@Z ENDP	; tnvx::mat4::translation
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?scaling@mat4@tnvx@@SA?AU12@MMM@Z
_TEXT	SEGMENT
__$ReturnUdt$ = 8
x$ = 16
y$ = 24
z$ = 32
?scaling@mat4@tnvx@@SA?AU12@MMM@Z PROC			; tnvx::mat4::scaling, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movaps	xmm4, xmm1
	xorps	xmm0, xmm0
	xorps	xmm1, xmm1
	unpcklps xmm4, xmm0
	unpcklps xmm4, xmm1
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; Line 81
	mov	rax, rcx
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movaps	xmm1, xmm2
	xorps	xmm2, xmm2
	unpcklps xmm1, xmm0
	movaps	xmm0, xmm3
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; Line 16
	movups	XMMWORD PTR [rcx], xmm4
	xorps	xmm3, xmm3
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	unpcklps xmm2, xmm1
	unpcklps xmm3, xmm0
	xorps	xmm1, xmm1
	movdqa	xmm0, XMMWORD PTR __xmm@3f800000000000000000000000000000
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; Line 16
	movups	XMMWORD PTR [rcx+16], xmm2
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	unpcklps xmm3, xmm1
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; Line 16
	movups	XMMWORD PTR [rcx+32], xmm3
	movups	XMMWORD PTR [rcx+48], xmm0
; Line 85
	ret	0
?scaling@mat4@tnvx@@SA?AU12@MMM@Z ENDP			; tnvx::mat4::scaling
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?scaling@mat4@tnvx@@SA?AU12@AEBUvec4@2@@Z
_TEXT	SEGMENT
__$ReturnUdt$ = 8
s$ = 16
?scaling@mat4@tnvx@@SA?AU12@AEBUvec4@2@@Z PROC		; tnvx::mat4::scaling, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movdqa	xmm2, XMMWORD PTR __xmm@000000003f8000000000000000000000
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; Line 96
	mov	rax, rcx
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 103
	mulps	xmm2, XMMWORD PTR [rdx]
; Line 23
	movdqa	xmm1, XMMWORD PTR __xmm@00000000000000003f80000000000000
; Line 103
	mulps	xmm1, XMMWORD PTR [rdx]
; Line 23
	movdqa	xmm0, XMMWORD PTR __xmm@0000000000000000000000003f800000
; Line 103
	mulps	xmm0, XMMWORD PTR [rdx]
; Line 23
	movdqa	xmm3, XMMWORD PTR __xmm@3f800000000000000000000000000000
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; Line 38
	movups	XMMWORD PTR [rcx+16], xmm1
	movups	XMMWORD PTR [rcx], xmm0
	movups	XMMWORD PTR [rcx+32], xmm2
	movups	XMMWORD PTR [rcx+48], xmm3
; Line 100
	ret	0
?scaling@mat4@tnvx@@SA?AU12@AEBUvec4@2@@Z ENDP		; tnvx::mat4::scaling
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?from_quat@mat4@tnvx@@SA?AU12@AEBUquat@2@@Z
_TEXT	SEGMENT
__$ReturnUdt$ = 32
q$ = 40
?from_quat@mat4@tnvx@@SA?AU12@AEBUquat@2@@Z PROC	; tnvx::mat4::from_quat, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; Line 104
$LN19:
	sub	rsp, 24
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\quat\quat_impl.hpp
; Line 32
	movups	xmm5, XMMWORD PTR [rdx]
	xorps	xmm1, xmm1
	movaps	XMMWORD PTR [rsp], xmm6
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 287
	movaps	xmm3, xmm5
; Line 23
	movdqa	xmm6, XMMWORD PTR __xmm@000000003f8000003f8000003f800000
; Line 287
	addps	xmm3, xmm5
; Line 288
	movaps	xmm2, xmm5
; Line 296
	movaps	xmm4, xmm5
	shufps	xmm4, xmm5, 201				; 000000c9H
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; Line 105
	mov	rax, rcx
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 297
	shufps	xmm5, xmm5, 255				; 000000ffH
	mulps	xmm2, xmm3
	mulps	xmm4, xmm3
	shufps	xmm3, xmm3, 210				; 000000d2H
	movaps	xmm0, xmm2
	mulps	xmm5, xmm3
	shufps	xmm0, xmm2, 193				; 000000c1H
	subps	xmm6, xmm0
	shufps	xmm2, xmm2, 218				; 000000daH
	subps	xmm6, xmm2
; Line 300
	movaps	xmm2, xmm5
	addps	xmm2, xmm4
; Line 302
	subps	xmm4, xmm5
	blendps	xmm6, xmm1, 8
; Line 305
	movaps	xmm0, xmm6
	shufps	xmm2, xmm2, 210				; 000000d2H
; Line 306
	movaps	xmm1, xmm6
	blendps	xmm0, xmm2, 2
	blendps	xmm0, xmm4, 4
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; Line 62
	movups	XMMWORD PTR [rcx], xmm0
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movdqa	xmm0, XMMWORD PTR __xmm@3f800000000000000000000000000000
; Line 307
	blendps	xmm6, xmm2, 1
	blendps	xmm6, xmm4, 2
	blendps	xmm1, xmm4, 1
	blendps	xmm1, xmm2, 4
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; Line 62
	movups	XMMWORD PTR [rcx+16], xmm1
	movups	XMMWORD PTR [rcx+32], xmm6
	movups	XMMWORD PTR [rcx+48], xmm0
; Line 106
	movaps	xmm6, XMMWORD PTR [rsp]
	add	rsp, 24
	ret	0
?from_quat@mat4@tnvx@@SA?AU12@AEBUquat@2@@Z ENDP	; tnvx::mat4::from_quat
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?col@mat4@tnvx@@QEBA?AUvec4@2@H@Z
_TEXT	SEGMENT
this$ = 8
__$ReturnUdt$ = 16
j$ = 24
?col@mat4@tnvx@@QEBA?AUvec4@2@H@Z PROC			; tnvx::mat4::col, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; Line 117
	movsxd	rax, r8d
	add	rax, rax
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\vec4_impl.hpp
; Line 22
	movups	xmm0, XMMWORD PTR [rcx+rax*8]
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; Line 117
	mov	rax, rdx
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\vec4_impl.hpp
; Line 22
	movups	XMMWORD PTR [rdx], xmm0
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; Line 118
	ret	0
?col@mat4@tnvx@@QEBA?AUvec4@2@H@Z ENDP			; tnvx::mat4::col
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?eval@mat4@tnvx@@QEBA?AUmf4@@XZ
_TEXT	SEGMENT
this$ = 8
__$ReturnUdt$ = 16
?eval@mat4@tnvx@@QEBA?AUmf4@@XZ PROC			; tnvx::mat4::eval, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; Line 133
	movups	xmm0, XMMWORD PTR [rcx]
	mov	rax, rdx
	movups	xmm1, XMMWORD PTR [rcx+16]
	movaps	XMMWORD PTR [rdx], xmm0
	movups	xmm0, XMMWORD PTR [rcx+32]
	movaps	XMMWORD PTR [rdx+16], xmm1
	movups	xmm1, XMMWORD PTR [rcx+48]
	movaps	XMMWORD PTR [rdx+32], xmm0
	movaps	XMMWORD PTR [rdx+48], xmm1
; Line 134
	ret	0
?eval@mat4@tnvx@@QEBA?AUmf4@@XZ ENDP			; tnvx::mat4::eval
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$with_w@Uvec4@tnvx@@U12@@tnvx@@YA?AU?$WithW@Uvec4@tnvx@@U12@@0@AEBUvec4@0@0@Z
_TEXT	SEGMENT
__$ReturnUdt$ = 8
l$ = 16
r$ = 24
??$with_w@Uvec4@tnvx@@U12@@tnvx@@YA?AU?$WithW@Uvec4@tnvx@@U12@@0@AEBUvec4@0@0@Z PROC ; tnvx::with_w<tnvx::vec4,tnvx::vec4>, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\with_w_impl.hpp
; Line 11
	movaps	xmm0, XMMWORD PTR [rdx]
; Line 27
	mov	rax, rcx
; Line 12
	movaps	xmm1, XMMWORD PTR [r8]
	movups	XMMWORD PTR [rcx], xmm0
	movups	XMMWORD PTR [rcx+16], xmm1
; Line 28
	ret	0
??$with_w@Uvec4@tnvx@@U12@@tnvx@@YA?AU?$WithW@Uvec4@tnvx@@U12@@0@AEBUvec4@0@0@Z ENDP ; tnvx::with_w<tnvx::vec4,tnvx::vec4>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0?$WithW@Uvec4@tnvx@@U12@@tnvx@@QEAA@AEIBUvec4@1@0@Z
_TEXT	SEGMENT
this$ = 8
l$ = 16
r$ = 24
??0?$WithW@Uvec4@tnvx@@U12@@tnvx@@QEAA@AEIBUvec4@1@0@Z PROC ; tnvx::WithW<tnvx::vec4,tnvx::vec4>::WithW<tnvx::vec4,tnvx::vec4>, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\with_w_impl.hpp
; Line 11
	movaps	xmm0, XMMWORD PTR [rdx]
; Line 14
	mov	rax, rcx
	movaps	xmm1, XMMWORD PTR [r8]
	movups	XMMWORD PTR [rcx], xmm0
	movups	XMMWORD PTR [rcx+16], xmm1
	ret	0
??0?$WithW@Uvec4@tnvx@@U12@@tnvx@@QEAA@AEIBUvec4@1@0@Z ENDP ; tnvx::WithW<tnvx::vec4,tnvx::vec4>::WithW<tnvx::vec4,tnvx::vec4>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?eval@?$WithW@Uvec4@tnvx@@U12@@tnvx@@QEBA?AT__m128@@XZ
_TEXT	SEGMENT
this$ = 8
__$ReturnUdt$ = 16
?eval@?$WithW@Uvec4@tnvx@@U12@@tnvx@@QEBA?AT__m128@@XZ PROC ; tnvx::WithW<tnvx::vec4,tnvx::vec4>::eval, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\with_w_impl.hpp
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 232
	movups	xmm0, XMMWORD PTR [rcx]
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\with_w_impl.hpp
; Line 20
	mov	rax, rdx
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 232
	blendps	xmm0, XMMWORD PTR [rcx+16], 8
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\with_w_impl.hpp
; Line 20
	movups	XMMWORD PTR [rdx], xmm0
; Line 21
	ret	0
?eval@?$WithW@Uvec4@tnvx@@U12@@tnvx@@QEBA?AT__m128@@XZ ENDP ; tnvx::WithW<tnvx::vec4,tnvx::vec4>::eval
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?0U?$WithW@Uvec4@tnvx@@U12@@tnvx@@@vec4@tnvx@@QEAA@AEBU?$WithW@Uvec4@tnvx@@U12@@1@@Z
_TEXT	SEGMENT
this$ = 8
e$ = 16
??$?0U?$WithW@Uvec4@tnvx@@U12@@tnvx@@@vec4@tnvx@@QEAA@AEBU?$WithW@Uvec4@tnvx@@U12@@1@@Z PROC ; tnvx::vec4::vec4<tnvx::WithW<tnvx::vec4,tnvx::vec4> >, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\vec4_impl.hpp
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 232
	movups	xmm0, XMMWORD PTR [rdx]
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\vec4_impl.hpp
; Line 66
	mov	rax, rcx
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 232
	blendps	xmm0, XMMWORD PTR [rdx+16], 8
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\with_w_impl.hpp
; Line 20
	movups	XMMWORD PTR [rcx], xmm0
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\vec4_impl.hpp
; Line 66
	ret	0
??$?0U?$WithW@Uvec4@tnvx@@U12@@tnvx@@@vec4@tnvx@@QEAA@AEBU?$WithW@Uvec4@tnvx@@U12@@1@@Z ENDP ; tnvx::vec4::vec4<tnvx::WithW<tnvx::vec4,tnvx::vec4> >
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$hadamard@Uvec4@tnvx@@U12@@tnvx@@YA?AU?$Hadamard@Uvec4@tnvx@@U12@@0@AEBUvec4@0@0@Z
_TEXT	SEGMENT
__$ReturnUdt$ = 8
l$ = 16
r$ = 24
??$hadamard@Uvec4@tnvx@@U12@@tnvx@@YA?AU?$Hadamard@Uvec4@tnvx@@U12@@0@AEBUvec4@0@0@Z PROC ; tnvx::hadamard<tnvx::vec4,tnvx::vec4>, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\hadamard_impl.hpp
; Line 11
	movaps	xmm0, XMMWORD PTR [rdx]
; Line 26
	mov	rax, rcx
; Line 11
	movaps	xmm1, XMMWORD PTR [r8]
	movups	XMMWORD PTR [rcx], xmm0
	movups	XMMWORD PTR [rcx+16], xmm1
; Line 27
	ret	0
??$hadamard@Uvec4@tnvx@@U12@@tnvx@@YA?AU?$Hadamard@Uvec4@tnvx@@U12@@0@AEBUvec4@0@0@Z ENDP ; tnvx::hadamard<tnvx::vec4,tnvx::vec4>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0?$Hadamard@Uvec4@tnvx@@U12@@tnvx@@QEAA@AEIBUvec4@1@0@Z
_TEXT	SEGMENT
this$ = 8
l$ = 16
r$ = 24
??0?$Hadamard@Uvec4@tnvx@@U12@@tnvx@@QEAA@AEIBUvec4@1@0@Z PROC ; tnvx::Hadamard<tnvx::vec4,tnvx::vec4>::Hadamard<tnvx::vec4,tnvx::vec4>, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\hadamard_impl.hpp
; Line 11
	movaps	xmm0, XMMWORD PTR [rdx]
; Line 13
	mov	rax, rcx
	movaps	xmm1, XMMWORD PTR [r8]
	movups	XMMWORD PTR [rcx], xmm0
	movups	XMMWORD PTR [rcx+16], xmm1
	ret	0
??0?$Hadamard@Uvec4@tnvx@@U12@@tnvx@@QEAA@AEIBUvec4@1@0@Z ENDP ; tnvx::Hadamard<tnvx::vec4,tnvx::vec4>::Hadamard<tnvx::vec4,tnvx::vec4>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?eval@?$Hadamard@Uvec4@tnvx@@U12@@tnvx@@QEBA?AT__m128@@XZ
_TEXT	SEGMENT
this$ = 8
__$ReturnUdt$ = 16
?eval@?$Hadamard@Uvec4@tnvx@@U12@@tnvx@@QEBA?AT__m128@@XZ PROC ; tnvx::Hadamard<tnvx::vec4,tnvx::vec4>::eval, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\hadamard_impl.hpp
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 103
	movups	xmm0, XMMWORD PTR [rcx+16]
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\hadamard_impl.hpp
; Line 19
	mov	rax, rdx
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 103
	mulps	xmm0, XMMWORD PTR [rcx]
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\hadamard_impl.hpp
; Line 19
	movups	XMMWORD PTR [rdx], xmm0
; Line 20
	ret	0
?eval@?$Hadamard@Uvec4@tnvx@@U12@@tnvx@@QEBA?AT__m128@@XZ ENDP ; tnvx::Hadamard<tnvx::vec4,tnvx::vec4>::eval
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?0U?$Hadamard@Uvec4@tnvx@@U12@@tnvx@@@vec4@tnvx@@QEAA@AEBU?$Hadamard@Uvec4@tnvx@@U12@@1@@Z
_TEXT	SEGMENT
this$ = 8
e$ = 16
??$?0U?$Hadamard@Uvec4@tnvx@@U12@@tnvx@@@vec4@tnvx@@QEAA@AEBU?$Hadamard@Uvec4@tnvx@@U12@@1@@Z PROC ; tnvx::vec4::vec4<tnvx::Hadamard<tnvx::vec4,tnvx::vec4> >, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\vec4_impl.hpp
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 103
	movups	xmm0, XMMWORD PTR [rdx+16]
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\vec4_impl.hpp
; Line 66
	mov	rax, rcx
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 103
	mulps	xmm0, XMMWORD PTR [rdx]
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\hadamard_impl.hpp
; Line 19
	movups	XMMWORD PTR [rcx], xmm0
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\vec4_impl.hpp
; Line 66
	ret	0
??$?0U?$Hadamard@Uvec4@tnvx@@U12@@tnvx@@@vec4@tnvx@@QEAA@AEBU?$Hadamard@Uvec4@tnvx@@U12@@1@@Z ENDP ; tnvx::vec4::vec4<tnvx::Hadamard<tnvx::vec4,tnvx::vec4> >
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT cg_mat_from_quat
_TEXT	SEGMENT
qa$ = 64
out$ = 72
n$ = 80
cg_mat_from_quat PROC					; COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 31
$LN41:
	sub	rsp, 56					; 00000038H
	movaps	XMMWORD PTR [rsp+32], xmm6
	xor	r9d, r9d
	movaps	XMMWORD PTR [rsp+16], xmm7
	mov	r10, rcx
; Line 32
	movdqa	xmm7, XMMWORD PTR __xmm@3f800000000000000000000000000000
	movaps	XMMWORD PTR [rsp], xmm8
	movdqa	xmm8, XMMWORD PTR __xmm@000000003f8000003f8000003f800000
	cmp	r8, 4
	jb	$LN36@cg_mat_fro
	mov	QWORD PTR [rsp+48], rbx
	xor	r11d, r11d
	lea	rbx, QWORD PTR [r8-3]
$LL31@cg_mat_fro:
; Line 33
	mov	rcx, r9
	xorps	xmm6, xmm6
	add	rcx, rcx
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 293
	movaps	xmm5, xmm8
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 33
	mov	rax, r9
	shl	rax, 6
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\quat\quat_impl.hpp
; Line 32
	movups	xmm4, XMMWORD PTR [r10+rcx*8]
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 287
	movaps	xmm2, xmm4
; Line 288
	movaps	xmm1, xmm4
	addps	xmm2, xmm4
; Line 296
	movaps	xmm3, xmm4
	shufps	xmm3, xmm4, 201				; 000000c9H
; Line 297
	shufps	xmm4, xmm4, 255				; 000000ffH
	mulps	xmm1, xmm2
	mulps	xmm3, xmm2
	shufps	xmm2, xmm2, 210				; 000000d2H
	mulps	xmm4, xmm2
	movaps	xmm0, xmm1
	shufps	xmm0, xmm1, 193				; 000000c1H
	subps	xmm5, xmm0
	shufps	xmm1, xmm1, 218				; 000000daH
; Line 300
	movaps	xmm2, xmm4
	addps	xmm2, xmm3
; Line 302
	subps	xmm3, xmm4
	subps	xmm5, xmm1
	shufps	xmm2, xmm2, 210				; 000000d2H
	blendps	xmm5, xmm6, 8
; Line 305
	movaps	xmm0, xmm5
; Line 306
	movaps	xmm1, xmm5
	blendps	xmm0, xmm2, 2
; Line 307
	blendps	xmm5, xmm2, 1
	blendps	xmm1, xmm3, 1
	blendps	xmm1, xmm2, 4
	blendps	xmm0, xmm3, 4
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 33
	movups	XMMWORD PTR [rdx+rax], xmm0
	movups	XMMWORD PTR [rdx+rax+16], xmm1
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 307
	blendps	xmm5, xmm3, 2
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 33
	movups	XMMWORD PTR [rdx+rax+32], xmm5
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 293
	movaps	xmm5, xmm8
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 33
	movups	XMMWORD PTR [rdx+rax+48], xmm7
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\quat\quat_impl.hpp
; Line 32
	movups	xmm4, XMMWORD PTR [r10+rcx*8+16]
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 287
	movaps	xmm2, xmm4
; Line 288
	movaps	xmm1, xmm4
	addps	xmm2, xmm4
; Line 296
	movaps	xmm3, xmm4
	shufps	xmm3, xmm4, 201				; 000000c9H
; Line 297
	shufps	xmm4, xmm4, 255				; 000000ffH
	mulps	xmm1, xmm2
	mulps	xmm3, xmm2
	shufps	xmm2, xmm2, 210				; 000000d2H
	movaps	xmm0, xmm1
	mulps	xmm4, xmm2
	shufps	xmm0, xmm1, 193				; 000000c1H
	subps	xmm5, xmm0
	shufps	xmm1, xmm1, 218				; 000000daH
; Line 300
	movaps	xmm2, xmm4
	addps	xmm2, xmm3
; Line 302
	subps	xmm3, xmm4
	subps	xmm5, xmm1
	shufps	xmm2, xmm2, 210				; 000000d2H
	blendps	xmm5, xmm6, 8
; Line 305
	movaps	xmm0, xmm5
; Line 306
	movaps	xmm1, xmm5
	blendps	xmm0, xmm2, 2
; Line 307
	blendps	xmm5, xmm2, 1
	blendps	xmm1, xmm3, 1
	blendps	xmm1, xmm2, 4
	blendps	xmm0, xmm3, 4
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 33
	movups	XMMWORD PTR [rdx+rax+64], xmm0
	movups	XMMWORD PTR [rdx+r11+80], xmm1
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 307
	blendps	xmm5, xmm3, 2
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 33
	movups	XMMWORD PTR [rdx+r11+96], xmm5
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 293
	movaps	xmm5, xmm8
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 33
	movups	XMMWORD PTR [rdx+r11+112], xmm7
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\quat\quat_impl.hpp
; Line 32
	movups	xmm4, XMMWORD PTR [r10+rcx*8+32]
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 287
	movaps	xmm2, xmm4
; Line 288
	movaps	xmm1, xmm4
	addps	xmm2, xmm4
	mulps	xmm1, xmm2
; Line 290
	movaps	xmm0, xmm1
	shufps	xmm0, xmm1, 193				; 000000c1H
; Line 293
	subps	xmm5, xmm0
	shufps	xmm1, xmm1, 218				; 000000daH
; Line 296
	movaps	xmm3, xmm4
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 33
	add	r9, 4
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 296
	shufps	xmm3, xmm4, 201				; 000000c9H
	mulps	xmm3, xmm2
	subps	xmm5, xmm1
; Line 297
	shufps	xmm2, xmm2, 210				; 000000d2H
	shufps	xmm4, xmm4, 255				; 000000ffH
	mulps	xmm4, xmm2
	blendps	xmm5, xmm6, 8
; Line 305
	movaps	xmm0, xmm5
; Line 306
	movaps	xmm1, xmm5
	movaps	xmm2, xmm4
	addps	xmm2, xmm3
	subps	xmm3, xmm4
	shufps	xmm2, xmm2, 210				; 000000d2H
; Line 307
	blendps	xmm5, xmm2, 1
	blendps	xmm0, xmm2, 2
	blendps	xmm1, xmm3, 1
	blendps	xmm1, xmm2, 4
	blendps	xmm5, xmm3, 2
	blendps	xmm0, xmm3, 4
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 33
	movups	XMMWORD PTR [rdx+r11+128], xmm0
	movups	XMMWORD PTR [rdx+r11+144], xmm1
	movups	XMMWORD PTR [rdx+r11+160], xmm5
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 293
	movaps	xmm5, xmm8
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 33
	movups	XMMWORD PTR [rdx+r11+176], xmm7
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\quat\quat_impl.hpp
; Line 32
	movups	xmm4, XMMWORD PTR [r10+rcx*8+48]
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 287
	movaps	xmm2, xmm4
; Line 288
	movaps	xmm1, xmm4
	addps	xmm2, xmm4
; Line 296
	movaps	xmm3, xmm4
	shufps	xmm3, xmm4, 201				; 000000c9H
; Line 297
	shufps	xmm4, xmm4, 255				; 000000ffH
	mulps	xmm1, xmm2
	mulps	xmm3, xmm2
	shufps	xmm2, xmm2, 210				; 000000d2H
	movaps	xmm0, xmm1
	mulps	xmm4, xmm2
	shufps	xmm0, xmm1, 193				; 000000c1H
	subps	xmm5, xmm0
	shufps	xmm1, xmm1, 218				; 000000daH
; Line 300
	movaps	xmm2, xmm4
	addps	xmm2, xmm3
; Line 302
	subps	xmm3, xmm4
	subps	xmm5, xmm1
	shufps	xmm2, xmm2, 210				; 000000d2H
	blendps	xmm5, xmm6, 8
; Line 305
	movaps	xmm0, xmm5
; Line 306
	movaps	xmm1, xmm5
	blendps	xmm0, xmm2, 2
	blendps	xmm1, xmm3, 1
	blendps	xmm0, xmm3, 4
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 33
	movups	XMMWORD PTR [rdx+r11+192], xmm0
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 307
	blendps	xmm5, xmm2, 1
	blendps	xmm1, xmm2, 4
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 33
	movups	XMMWORD PTR [rdx+r11+208], xmm1
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 307
	blendps	xmm5, xmm3, 2
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 33
	movups	XMMWORD PTR [rdx+r11+224], xmm5
	movups	XMMWORD PTR [rdx+r11+240], xmm7
	add	r11, 256				; 00000100H
	cmp	r9, rbx
	jb	$LL31@cg_mat_fro
	mov	rbx, QWORD PTR [rsp+48]
$LN36@cg_mat_fro:
; Line 32
	cmp	r9, r8
	jae	$LN29@cg_mat_fro
$LC4@cg_mat_fro:
	xorps	xmm1, xmm1
; Line 33
	mov	rax, r9
	add	rax, rax
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 293
	movaps	xmm6, xmm8
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\quat\quat_impl.hpp
; Line 32
	movups	xmm5, XMMWORD PTR [r10+rax*8]
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 33
	mov	rax, r9
	shl	rax, 6
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 287
	movaps	xmm3, xmm5
	addps	xmm3, xmm5
; Line 288
	movaps	xmm2, xmm5
; Line 296
	movaps	xmm4, xmm5
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 32
	inc	r9
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 296
	shufps	xmm4, xmm5, 201				; 000000c9H
; Line 297
	shufps	xmm5, xmm5, 255				; 000000ffH
	mulps	xmm2, xmm3
	mulps	xmm4, xmm3
	shufps	xmm3, xmm3, 210				; 000000d2H
	mulps	xmm5, xmm3
	movaps	xmm0, xmm2
	shufps	xmm0, xmm2, 193				; 000000c1H
	shufps	xmm2, xmm2, 218				; 000000daH
	subps	xmm6, xmm0
	subps	xmm6, xmm2
; Line 300
	movaps	xmm2, xmm5
	addps	xmm2, xmm4
; Line 302
	subps	xmm4, xmm5
	blendps	xmm6, xmm1, 8
	shufps	xmm2, xmm2, 210				; 000000d2H
; Line 305
	movaps	xmm0, xmm6
; Line 306
	movaps	xmm1, xmm6
	blendps	xmm0, xmm2, 2
	blendps	xmm1, xmm4, 1
	blendps	xmm0, xmm4, 4
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 33
	movups	XMMWORD PTR [rdx+rax], xmm0
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 307
	blendps	xmm6, xmm2, 1
	blendps	xmm1, xmm2, 4
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 33
	movups	XMMWORD PTR [rdx+rax+16], xmm1
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 307
	blendps	xmm6, xmm4, 2
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 33
	movups	XMMWORD PTR [rdx+rax+32], xmm6
	movups	XMMWORD PTR [rdx+rax+48], xmm7
	cmp	r9, r8
	jb	$LC4@cg_mat_fro
$LN29@cg_mat_fro:
; Line 34
	movaps	xmm6, XMMWORD PTR [rsp+32]
	movaps	xmm7, XMMWORD PTR [rsp+16]
	movaps	xmm8, XMMWORD PTR [rsp]
	add	rsp, 56					; 00000038H
	ret	0
cg_mat_from_quat ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT cg_mat_translation
_TEXT	SEGMENT
va$ = 16
out$ = 24
n$ = 32
cg_mat_translation PROC					; COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 37
$LN95:
	sub	rsp, 8
; Line 38
	movdqa	xmm1, XMMWORD PTR __xmm@0000000000000000000000003f800000
	xor	r9d, r9d
	movdqa	xmm2, XMMWORD PTR __xmm@00000000000000003f80000000000000
	mov	r10, r8
	movdqa	xmm3, XMMWORD PTR __xmm@000000003f8000000000000000000000
	mov	r11, rcx
	movdqa	xmm4, XMMWORD PTR __xmm@3f8000003f8000003f8000003f800000
	cmp	r8, 4
	jb	$LN90@cg_mat_tra
	mov	QWORD PTR [rsp], rbx
	lea	rbx, QWORD PTR [r8-3]
	xor	r8d, r8d
	npad	14
$LL85@cg_mat_tra:
; Line 39
	mov	rcx, r9
	lea	r8, QWORD PTR [r8+256]
	add	rcx, rcx
	mov	rax, r9
	shl	rax, 6
	add	r9, 4
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\with_w_impl.hpp
; Line 11
	movups	xmm0, XMMWORD PTR [r11+rcx*8]
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 39
	movups	XMMWORD PTR [rdx+rax], xmm1
	movups	XMMWORD PTR [rdx+rax+16], xmm2
	movups	XMMWORD PTR [rdx+rax+32], xmm3
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 232
	blendps	xmm0, xmm4, 8
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 39
	movups	XMMWORD PTR [rdx+rax+48], xmm0
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\with_w_impl.hpp
; Line 11
	movups	xmm0, XMMWORD PTR [r11+rcx*8+16]
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 39
	movups	XMMWORD PTR [rdx+rax+64], xmm1
	movups	XMMWORD PTR [rdx+r8-176], xmm2
	movups	XMMWORD PTR [rdx+r8-160], xmm3
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 232
	blendps	xmm0, xmm4, 8
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 39
	movups	XMMWORD PTR [rdx+r8-144], xmm0
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\with_w_impl.hpp
; Line 11
	movups	xmm0, XMMWORD PTR [r11+rcx*8+32]
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 39
	movups	XMMWORD PTR [rdx+r8-128], xmm1
	movups	XMMWORD PTR [rdx+r8-112], xmm2
	movups	XMMWORD PTR [rdx+r8-96], xmm3
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 232
	blendps	xmm0, xmm4, 8
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 39
	movups	XMMWORD PTR [rdx+r8-80], xmm0
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\with_w_impl.hpp
; Line 11
	movups	xmm0, XMMWORD PTR [r11+rcx*8+48]
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 39
	movups	XMMWORD PTR [rdx+r8-64], xmm1
	movups	XMMWORD PTR [rdx+r8-48], xmm2
	movups	XMMWORD PTR [rdx+r8-32], xmm3
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 232
	blendps	xmm0, xmm4, 8
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 39
	movups	XMMWORD PTR [rdx+r8-16], xmm0
	cmp	r9, rbx
	jb	$LL85@cg_mat_tra
	mov	rbx, QWORD PTR [rsp]
$LN90@cg_mat_tra:
; Line 38
	cmp	r9, r10
	jae	SHORT $LN83@cg_mat_tra
$LC4@cg_mat_tra:
; Line 39
	mov	rax, r9
	add	rax, rax
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\with_w_impl.hpp
; Line 11
	movups	xmm0, XMMWORD PTR [r11+rax*8]
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 39
	mov	rax, r9
	shl	rax, 6
	inc	r9
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 232
	blendps	xmm0, xmm4, 8
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 39
	movups	XMMWORD PTR [rdx+rax], xmm1
	movups	XMMWORD PTR [rdx+rax+16], xmm2
	movups	XMMWORD PTR [rdx+rax+32], xmm3
	movups	XMMWORD PTR [rdx+rax+48], xmm0
	cmp	r9, r10
	jb	SHORT $LC4@cg_mat_tra
$LN83@cg_mat_tra:
; Line 40
	add	rsp, 8
	ret	0
cg_mat_translation ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT cg_mat_scaling_vec
_TEXT	SEGMENT
va$ = 32
out$ = 40
n$ = 48
cg_mat_scaling_vec PROC					; COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 43
$LN138:
	sub	rsp, 24
; Line 44
	movdqa	xmm3, XMMWORD PTR __xmm@0000000000000000000000003f800000
	xor	r9d, r9d
	movdqa	xmm4, XMMWORD PTR __xmm@00000000000000003f80000000000000
	mov	r10, rcx
	movdqa	xmm5, XMMWORD PTR __xmm@000000003f8000000000000000000000
	movaps	XMMWORD PTR [rsp], xmm6
	movdqa	xmm6, XMMWORD PTR __xmm@3f800000000000000000000000000000
	cmp	r8, 4
	jb	$LN133@cg_mat_sca
	mov	QWORD PTR [rsp+16], rbx
	xor	r11d, r11d
	lea	rbx, QWORD PTR [r8-3]
	npad	12
$LL128@cg_mat_sca:
; Line 45
	mov	rcx, r9
	lea	r11, QWORD PTR [r11+256]
	add	rcx, rcx
	mov	rax, r9
	shl	rax, 6
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 103
	movaps	xmm0, xmm3
	movaps	xmm1, xmm4
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 45
	add	r9, 4
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 103
	mulps	xmm0, XMMWORD PTR [r10+rcx*8]
	mulps	xmm1, XMMWORD PTR [r10+rcx*8]
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\hadamard_impl.hpp
; Line 11
	movups	xmm2, XMMWORD PTR [r10+rcx*8]
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 45
	movups	XMMWORD PTR [rdx+rax], xmm0
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 103
	movaps	xmm0, xmm3
	mulps	xmm2, xmm5
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 45
	movups	XMMWORD PTR [rdx+rax+16], xmm1
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 103
	movaps	xmm1, xmm4
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 45
	movups	XMMWORD PTR [rdx+rax+32], xmm2
	movups	XMMWORD PTR [rdx+rax+48], xmm6
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 103
	mulps	xmm0, XMMWORD PTR [r10+rcx*8+16]
	mulps	xmm1, XMMWORD PTR [r10+rcx*8+16]
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\hadamard_impl.hpp
; Line 11
	movups	xmm2, XMMWORD PTR [r10+rcx*8+16]
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 45
	movups	XMMWORD PTR [rdx+rax+64], xmm0
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 103
	movaps	xmm0, xmm3
	mulps	xmm2, xmm5
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 45
	movups	XMMWORD PTR [rdx+r11-176], xmm1
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 103
	movaps	xmm1, xmm4
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 45
	movups	XMMWORD PTR [rdx+r11-160], xmm2
	movups	XMMWORD PTR [rdx+r11-144], xmm6
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 103
	mulps	xmm0, XMMWORD PTR [r10+rcx*8+32]
	mulps	xmm1, XMMWORD PTR [r10+rcx*8+32]
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\hadamard_impl.hpp
; Line 11
	movups	xmm2, XMMWORD PTR [r10+rcx*8+32]
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 45
	movups	XMMWORD PTR [rdx+r11-128], xmm0
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 103
	movaps	xmm0, xmm3
	mulps	xmm2, xmm5
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 45
	movups	XMMWORD PTR [rdx+r11-112], xmm1
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 103
	movaps	xmm1, xmm4
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 45
	movups	XMMWORD PTR [rdx+r11-96], xmm2
	movups	XMMWORD PTR [rdx+r11-80], xmm6
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\hadamard_impl.hpp
; Line 11
	movups	xmm2, XMMWORD PTR [r10+rcx*8+48]
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 103
	mulps	xmm1, XMMWORD PTR [r10+rcx*8+48]
	mulps	xmm0, XMMWORD PTR [r10+rcx*8+48]
	mulps	xmm2, xmm5
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 45
	movups	XMMWORD PTR [rdx+r11-48], xmm1
	movups	XMMWORD PTR [rdx+r11-64], xmm0
	movups	XMMWORD PTR [rdx+r11-16], xmm6
	movups	XMMWORD PTR [rdx+r11-32], xmm2
	cmp	r9, rbx
	jb	$LL128@cg_mat_sca
	mov	rbx, QWORD PTR [rsp+16]
$LN133@cg_mat_sca:
; Line 44
	cmp	r9, r8
	jae	SHORT $LN126@cg_mat_sca
$LC4@cg_mat_sca:
; Line 45
	mov	rax, r9
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 103
	movaps	xmm1, xmm4
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 45
	add	rax, rax
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 103
	movaps	xmm0, xmm3
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\hadamard_impl.hpp
; Line 11
	movups	xmm2, XMMWORD PTR [r10+rax*8]
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 103
	mulps	xmm1, XMMWORD PTR [r10+rax*8]
	mulps	xmm0, XMMWORD PTR [r10+rax*8]
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 45
	mov	rax, r9
	shl	rax, 6
	inc	r9
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 103
	mulps	xmm2, xmm5
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 45
	movups	XMMWORD PTR [rdx+rax], xmm0
	movups	XMMWORD PTR [rdx+rax+16], xmm1
	movups	XMMWORD PTR [rdx+rax+32], xmm2
	movups	XMMWORD PTR [rdx+rax+48], xmm6
	cmp	r9, r8
	jb	SHORT $LC4@cg_mat_sca
$LN126@cg_mat_sca:
; Line 46
	movaps	xmm6, XMMWORD PTR [rsp]
	add	rsp, 24
	ret	0
cg_mat_scaling_vec ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT cg_mat_scaling_scalar
_TEXT	SEGMENT
sx$ = 16
sy$ = 24
sz$ = 32
out$ = 40
n$ = 48
cg_mat_scaling_scalar PROC				; COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 50
$LN39:
	sub	rsp, 8
	mov	r11, QWORD PTR n$[rsp]
	mov	r10, r9
; Line 51
	movdqa	xmm5, XMMWORD PTR __xmm@3f800000000000000000000000000000
	xor	r9d, r9d
	cmp	r11, 4
	jb	$LN34@cg_mat_sca
	mov	QWORD PTR [rsp+16], rbx
	xor	ebx, ebx
	mov	QWORD PTR [rsp], rdi
	lea	rdi, QWORD PTR [r11-3]
$LL29@cg_mat_sca:
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movss	xmm1, DWORD PTR [rdx+r9*4]
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 52
	lea	rbx, QWORD PTR [rbx+256]
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movss	xmm0, DWORD PTR [r8+r9*4]
	xorps	xmm3, xmm3
	movss	xmm2, DWORD PTR [rcx+r9*4]
	xorps	xmm4, xmm4
	unpcklps xmm4, xmm1
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 52
	mov	rax, r9
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	unpcklps xmm3, xmm0
	xorps	xmm1, xmm1
	unpcklps xmm3, xmm1
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 52
	shl	rax, 6
	movups	XMMWORD PTR [r10+rax], xmm2
	movups	XMMWORD PTR [r10+rax+16], xmm4
	xorps	xmm4, xmm4
	movups	XMMWORD PTR [r10+rax+32], xmm3
	xorps	xmm3, xmm3
	movups	XMMWORD PTR [r10+rax+48], xmm5
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movss	xmm1, DWORD PTR [rdx+r9*4+4]
	movss	xmm0, DWORD PTR [r8+r9*4+4]
	movss	xmm2, DWORD PTR [rcx+r9*4+4]
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 52
	movups	XMMWORD PTR [r10+rax+64], xmm2
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	unpcklps xmm4, xmm1
	xorps	xmm1, xmm1
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 52
	movups	XMMWORD PTR [r10+rbx-176], xmm4
	xorps	xmm4, xmm4
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	unpcklps xmm3, xmm0
	unpcklps xmm3, xmm1
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 52
	movups	XMMWORD PTR [r10+rbx-160], xmm3
	xorps	xmm3, xmm3
	movups	XMMWORD PTR [r10+rbx-144], xmm5
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movss	xmm1, DWORD PTR [rdx+r9*4+8]
	movss	xmm0, DWORD PTR [r8+r9*4+8]
	movss	xmm2, DWORD PTR [rcx+r9*4+8]
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 52
	movups	XMMWORD PTR [r10+rbx-128], xmm2
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	unpcklps xmm4, xmm1
	xorps	xmm1, xmm1
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 52
	movups	XMMWORD PTR [r10+rbx-112], xmm4
	xorps	xmm4, xmm4
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	unpcklps xmm3, xmm0
	unpcklps xmm3, xmm1
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 52
	movups	XMMWORD PTR [r10+rbx-96], xmm3
	xorps	xmm3, xmm3
	movups	XMMWORD PTR [r10+rbx-80], xmm5
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movss	xmm1, DWORD PTR [rdx+r9*4+12]
	movss	xmm0, DWORD PTR [r8+r9*4+12]
	movss	xmm2, DWORD PTR [rcx+r9*4+12]
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 52
	add	r9, 4
	movups	XMMWORD PTR [r10+rbx-64], xmm2
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	unpcklps xmm4, xmm1
	xorps	xmm1, xmm1
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 52
	movups	XMMWORD PTR [r10+rbx-48], xmm4
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	unpcklps xmm3, xmm0
	unpcklps xmm3, xmm1
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 52
	movups	XMMWORD PTR [r10+rbx-32], xmm3
	movups	XMMWORD PTR [r10+rbx-16], xmm5
	cmp	r9, rdi
	jb	$LL29@cg_mat_sca
	mov	rdi, QWORD PTR [rsp]
	mov	rbx, QWORD PTR [rsp+16]
$LN34@cg_mat_sca:
; Line 51
	cmp	r9, r11
	jae	SHORT $LN27@cg_mat_sca
$LC4@cg_mat_sca:
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movss	xmm1, DWORD PTR [rdx+r9*4]
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 52
	mov	rax, r9
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movss	xmm0, DWORD PTR [r8+r9*4]
	xorps	xmm3, xmm3
	movss	xmm2, DWORD PTR [rcx+r9*4]
	xorps	xmm4, xmm4
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 52
	shl	rax, 6
	inc	r9
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	unpcklps xmm4, xmm1
	xorps	xmm1, xmm1
	unpcklps xmm3, xmm0
	unpcklps xmm3, xmm1
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 52
	movups	XMMWORD PTR [r10+rax], xmm2
	movups	XMMWORD PTR [r10+rax+16], xmm4
	movups	XMMWORD PTR [r10+rax+32], xmm3
	movups	XMMWORD PTR [r10+rax+48], xmm5
	cmp	r9, r11
	jb	SHORT $LC4@cg_mat_sca
$LN27@cg_mat_sca:
; Line 53
	add	rsp, 8
	ret	0
cg_mat_scaling_scalar ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT cg_mat_identity
_TEXT	SEGMENT
out$ = 8
n$ = 16
cg_mat_identity PROC					; COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 56
	xor	r8d, r8d
; Line 57
	test	rdx, rdx
	je	SHORT $LN3@cg_mat_ide
	movdqa	xmm0, XMMWORD PTR __xmm@0000000000000000000000003f800000
	movdqa	xmm1, XMMWORD PTR __xmm@00000000000000003f80000000000000
	movdqa	xmm2, XMMWORD PTR __xmm@000000003f8000000000000000000000
	movdqa	xmm3, XMMWORD PTR __xmm@3f800000000000000000000000000000
	npad	8
$LL4@cg_mat_ide:
; Line 58
	mov	rax, r8
	inc	r8
	shl	rax, 6
	movups	XMMWORD PTR [rcx+rax], xmm0
	movups	XMMWORD PTR [rcx+rax+16], xmm1
	movups	XMMWORD PTR [rcx+rax+32], xmm2
	movups	XMMWORD PTR [rcx+rax+48], xmm3
	cmp	r8, rdx
	jb	SHORT $LL4@cg_mat_ide
$LN3@cg_mat_ide:
; Line 59
	ret	0
cg_mat_identity ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT cg_mat_at
_TEXT	SEGMENT
ma$ = 8
out$ = 16
n$ = 24
cg_mat_at PROC						; COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 63
	xor	r9d, r9d
	cmp	r8, 4
	jb	SHORT $LN23@cg_mat_at
	lea	r10, QWORD PTR [r8-3]
	npad	3
$LL18@cg_mat_at:
; Line 64
	mov	rax, r9
	shl	rax, 6
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 73
	movss	xmm0, DWORD PTR [rcx+rax+24]
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 64
	movss	DWORD PTR [rdx+r9*4], xmm0
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 73
	movss	xmm1, DWORD PTR [rcx+rax+88]
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 64
	movss	DWORD PTR [rdx+r9*4+4], xmm1
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 73
	movss	xmm0, DWORD PTR [rcx+rax+152]
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 64
	movss	DWORD PTR [rdx+r9*4+8], xmm0
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 73
	movss	xmm1, DWORD PTR [rcx+rax+216]
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 64
	movss	DWORD PTR [rdx+r9*4+12], xmm1
	add	r9, 4
	cmp	r9, r10
	jb	SHORT $LL18@cg_mat_at
$LN23@cg_mat_at:
; Line 63
	cmp	r9, r8
	jae	SHORT $LN16@cg_mat_at
$LC4@cg_mat_at:
; Line 64
	mov	rax, r9
	shl	rax, 6
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 73
	movss	xmm0, DWORD PTR [rcx+rax+24]
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 64
	movss	DWORD PTR [rdx+r9*4], xmm0
	inc	r9
	cmp	r9, r8
	jb	SHORT $LC4@cg_mat_at
$LN16@cg_mat_at:
; Line 65
	ret	0
cg_mat_at ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$at@$01$00@mat4@tnvx@@QEBAMXZ
_TEXT	SEGMENT
this$ = 8
??$at@$01$00@mat4@tnvx@@QEBAMXZ PROC			; tnvx::mat4::at<2,1>, COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 73
	movss	xmm0, DWORD PTR [rcx+24]
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\mat\mat4_impl.hpp
; Line 128
	ret	0
??$at@$01$00@mat4@tnvx@@QEBAMXZ ENDP			; tnvx::mat4::at<2,1>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT cg_mat_col
_TEXT	SEGMENT
ma$ = 8
out$ = 16
n$ = 24
cg_mat_col PROC						; COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 68
	xor	eax, eax
	mov	r10, rdx
; Line 69
	test	r8, r8
	je	SHORT $LN3@cg_mat_col
	npad	6
$LL4@cg_mat_col:
; Line 70
	mov	r9, rax
	mov	rdx, rax
	shl	r9, 6
	add	rdx, rdx
	inc	rax
	movups	xmm0, XMMWORD PTR [rcx+r9+16]
	movups	XMMWORD PTR [r10+rdx*8], xmm0
	cmp	rax, r8
	jb	SHORT $LL4@cg_mat_col
$LN3@cg_mat_col:
; Line 71
	ret	0
cg_mat_col ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT cg_mat_from_quat_value
_TEXT	SEGMENT
__$ReturnAddress$ = 32
q$ = 40
cg_mat_from_quat_value PROC				; COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 74
$LN24:
	sub	rsp, 24
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\quat\quat_impl.hpp
; Line 32
	movups	xmm5, XMMWORD PTR [rdx]
	xorps	xmm1, xmm1
	movaps	XMMWORD PTR [rsp], xmm6
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 287
	movaps	xmm3, xmm5
; Line 23
	movdqa	xmm6, XMMWORD PTR __xmm@000000003f8000003f8000003f800000
; Line 287
	addps	xmm3, xmm5
; Line 288
	movaps	xmm2, xmm5
; Line 296
	movaps	xmm4, xmm5
	shufps	xmm4, xmm5, 201				; 000000c9H
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 75
	mov	rax, rcx
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 297
	shufps	xmm5, xmm5, 255				; 000000ffH
	mulps	xmm2, xmm3
	mulps	xmm4, xmm3
	shufps	xmm3, xmm3, 210				; 000000d2H
	movaps	xmm0, xmm2
	mulps	xmm5, xmm3
	shufps	xmm0, xmm2, 193				; 000000c1H
	subps	xmm6, xmm0
	shufps	xmm2, xmm2, 218				; 000000daH
	subps	xmm6, xmm2
; Line 300
	movaps	xmm2, xmm5
	addps	xmm2, xmm4
; Line 302
	subps	xmm4, xmm5
	blendps	xmm6, xmm1, 8
; Line 305
	movaps	xmm0, xmm6
	shufps	xmm2, xmm2, 210				; 000000d2H
; Line 306
	movaps	xmm1, xmm6
	blendps	xmm0, xmm2, 2
	blendps	xmm0, xmm4, 4
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 75
	movups	XMMWORD PTR [rcx], xmm0
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movdqa	xmm0, XMMWORD PTR __xmm@3f800000000000000000000000000000
; Line 307
	blendps	xmm6, xmm2, 1
	blendps	xmm6, xmm4, 2
	blendps	xmm1, xmm4, 1
	blendps	xmm1, xmm2, 4
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 75
	movups	XMMWORD PTR [rcx+16], xmm1
	movups	XMMWORD PTR [rcx+32], xmm6
	movups	XMMWORD PTR [rcx+48], xmm0
; Line 76
	movaps	xmm6, XMMWORD PTR [rsp]
	add	rsp, 24
	ret	0
cg_mat_from_quat_value ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT cg_mat_translation_value
_TEXT	SEGMENT
__$ReturnAddress$ = 8
t$ = 16
cg_mat_translation_value PROC				; COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\vec\with_w_impl.hpp
; Line 11
	movups	xmm3, XMMWORD PTR [rdx]
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 80
	mov	rax, rcx
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 232
	blendps	xmm3, XMMWORD PTR __xmm@3f8000003f8000003f8000003f800000, 8
; Line 23
	movdqa	xmm2, XMMWORD PTR __xmm@000000003f8000000000000000000000
	movdqa	xmm1, XMMWORD PTR __xmm@00000000000000003f80000000000000
	movdqa	xmm0, XMMWORD PTR __xmm@0000000000000000000000003f800000
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 80
	movups	XMMWORD PTR [rcx+48], xmm3
	movups	XMMWORD PTR [rcx], xmm0
	movups	XMMWORD PTR [rcx+16], xmm1
	movups	XMMWORD PTR [rcx+32], xmm2
; Line 81
	ret	0
cg_mat_translation_value ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT cg_mat_scaling_scalar_value
_TEXT	SEGMENT
__$ReturnAddress$ = 8
x$ = 16
y$ = 24
z$ = 32
cg_mat_scaling_scalar_value PROC			; COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movaps	xmm4, xmm1
	xorps	xmm0, xmm0
	xorps	xmm1, xmm1
	unpcklps xmm4, xmm0
	unpcklps xmm4, xmm1
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 85
	mov	rax, rcx
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movaps	xmm1, xmm2
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 85
	movups	XMMWORD PTR [rcx], xmm4
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	unpcklps xmm1, xmm0
	xorps	xmm2, xmm2
	movaps	xmm0, xmm3
	unpcklps xmm2, xmm1
	xorps	xmm3, xmm3
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 85
	movups	XMMWORD PTR [rcx+16], xmm2
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	unpcklps xmm3, xmm0
	xorps	xmm1, xmm1
	movdqa	xmm0, XMMWORD PTR __xmm@3f800000000000000000000000000000
	unpcklps xmm3, xmm1
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 85
	movups	XMMWORD PTR [rcx+32], xmm3
	movups	XMMWORD PTR [rcx+48], xmm0
; Line 86
	ret	0
cg_mat_scaling_scalar_value ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT cg_mat_identity_value
_TEXT	SEGMENT
__$ReturnAddress$ = 8
cg_mat_identity_value PROC				; COMDAT
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movdqa	xmm0, XMMWORD PTR __xmm@0000000000000000000000003f800000
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 90
	mov	rax, rcx
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movdqa	xmm1, XMMWORD PTR __xmm@00000000000000003f80000000000000
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 90
	movups	XMMWORD PTR [rcx], xmm0
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movdqa	xmm0, XMMWORD PTR __xmm@000000003f8000000000000000000000
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 90
	movups	XMMWORD PTR [rcx+16], xmm1
; File C:\Users\artem_zyktin\projects\tenvex\src\include\tenvex\detail\core\core_sse.h
; Line 23
	movdqa	xmm1, XMMWORD PTR __xmm@3f800000000000000000000000000000
; File C:\Users\artem_zyktin\projects\tenvex\src\codegen\cg_mat.cpp
; Line 90
	movups	XMMWORD PTR [rcx+32], xmm0
	movups	XMMWORD PTR [rcx+48], xmm1
; Line 91
	ret	0
cg_mat_identity_value ENDP
_TEXT	ENDS
END
