; Microsoft (R) C/C++ Optimizing Compiler Version 19.51.36248 for x64
; cl /nologo /c /O2 /std:c++20 /EHsc /W3 /Isrc\tenvex /FA cg_quat.cpp
; Listing generated by Microsoft (R) Optimizing Compiler Version 19.51.36248.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?scalar@detail@tnvx@@YA?AT__m128@@M@Z		; tnvx::detail::scalar
PUBLIC	?conjugate@detail@tnvx@@YA?AT__m128@@T3@@Z	; tnvx::detail::conjugate
PUBLIC	?add@detail@tnvx@@YA?AT__m128@@T3@0@Z		; tnvx::detail::add
PUBLIC	?mul@detail@tnvx@@YA?AT__m128@@T3@0@Z		; tnvx::detail::mul
PUBLIC	?dot4@detail@tnvx@@YA?AT__m128@@T3@0@Z		; tnvx::detail::dot4
PUBLIC	?magnitude4_sq@detail@tnvx@@YA?AT__m128@@T3@@Z	; tnvx::detail::magnitude4_sq
PUBLIC	?cross3@detail@tnvx@@YA?AT__m128@@T3@0@Z	; tnvx::detail::cross3
PUBLIC	?quat_mul@detail@tnvx@@YA?AT__m128@@T3@0@Z	; tnvx::detail::quat_mul
PUBLIC	?rotate@detail@tnvx@@YA?AT__m128@@T3@0@Z	; tnvx::detail::rotate
PUBLIC	?inverse@detail@tnvx@@YA?AT__m128@@T3@@Z	; tnvx::detail::inverse
PUBLIC	??0Scalar@tnvx@@QEAA@M@Z			; tnvx::Scalar::Scalar
PUBLIC	?eval@Scalar@tnvx@@QEBA?AT__m128@@XZ		; tnvx::Scalar::eval
PUBLIC	?eval@vec4@tnvx@@QEBA?AT__m128@@XZ		; tnvx::vec4::eval
PUBLIC	?eval@quat@tnvx@@QEBA?AT__m128@@XZ		; tnvx::quat::eval
PUBLIC	cg_hamilton
PUBLIC	??$?DUquat@tnvx@@U01@@tnvx@@YA?AU?$QuatMul@Uquat@tnvx@@U12@@0@AEBUquat@0@0@Z ; tnvx::operator*<tnvx::quat,tnvx::quat>
PUBLIC	??0?$QuatMul@Uquat@tnvx@@U12@@tnvx@@QEAA@AEIBUquat@1@0@Z ; tnvx::QuatMul<tnvx::quat,tnvx::quat>::QuatMul<tnvx::quat,tnvx::quat>
PUBLIC	?eval@?$QuatMul@Uquat@tnvx@@U12@@tnvx@@QEBA?AT__m128@@XZ ; tnvx::QuatMul<tnvx::quat,tnvx::quat>::eval
PUBLIC	cg_rotate
PUBLIC	??$rotate@Uvec4@tnvx@@Uquat@2@@tnvx@@YA?AU?$Rotate@Uvec4@tnvx@@Uquat@2@@0@AEBUvec4@0@AEBUquat@0@@Z ; tnvx::rotate<tnvx::vec4,tnvx::quat>
PUBLIC	??0?$Rotate@Uvec4@tnvx@@Uquat@2@@tnvx@@QEAA@AEIBUvec4@1@AEIBUquat@1@@Z ; tnvx::Rotate<tnvx::vec4,tnvx::quat>::Rotate<tnvx::vec4,tnvx::quat>
PUBLIC	?eval@?$Rotate@Uvec4@tnvx@@Uquat@2@@tnvx@@QEBA?AT__m128@@XZ ; tnvx::Rotate<tnvx::vec4,tnvx::quat>::eval
PUBLIC	cg_conj_scale
PUBLIC	??$conjugate@Uquat@tnvx@@@tnvx@@YA?AU?$Conjugate@Uquat@tnvx@@@0@AEBUquat@0@@Z ; tnvx::conjugate<tnvx::quat>
PUBLIC	??0?$Conjugate@Uquat@tnvx@@@tnvx@@QEAA@AEIBUquat@1@@Z ; tnvx::Conjugate<tnvx::quat>::Conjugate<tnvx::quat>
PUBLIC	?eval@?$Conjugate@Uquat@tnvx@@@tnvx@@QEBA?AT__m128@@XZ ; tnvx::Conjugate<tnvx::quat>::eval
PUBLIC	??$?DU?$Conjugate@Uquat@tnvx@@@tnvx@@@tnvx@@YA?AU?$Mul@U?$Conjugate@Uquat@tnvx@@@tnvx@@UScalar@2@@0@AEBU?$Conjugate@Uquat@tnvx@@@0@M@Z ; tnvx::operator*<tnvx::Conjugate<tnvx::quat> >
PUBLIC	??0?$Mul@U?$Conjugate@Uquat@tnvx@@@tnvx@@UScalar@2@@tnvx@@QEAA@AEIBU?$Conjugate@Uquat@tnvx@@@1@AEIBUScalar@1@@Z ; tnvx::Mul<tnvx::Conjugate<tnvx::quat>,tnvx::Scalar>::Mul<tnvx::Conjugate<tnvx::quat>,tnvx::Scalar>
PUBLIC	?eval@?$Mul@U?$Conjugate@Uquat@tnvx@@@tnvx@@UScalar@2@@tnvx@@QEBA?AT__m128@@XZ ; tnvx::Mul<tnvx::Conjugate<tnvx::quat>,tnvx::Scalar>::eval
PUBLIC	cg_quat_inverse
PUBLIC	??$inverse@Uquat@tnvx@@@tnvx@@YA?AU?$Inverse@Uquat@tnvx@@@0@AEBUquat@0@@Z ; tnvx::inverse<tnvx::quat>
PUBLIC	??0?$Inverse@Uquat@tnvx@@@tnvx@@QEAA@AEIBUquat@1@@Z ; tnvx::Inverse<tnvx::quat>::Inverse<tnvx::quat>
PUBLIC	?eval@?$Inverse@Uquat@tnvx@@@tnvx@@QEBA?AT__m128@@XZ ; tnvx::Inverse<tnvx::quat>::eval
PUBLIC	__xmm@00000000800000008000000080000000
PUBLIC	__xmm@40000000400000004000000040000000
PUBLIC	__xmm@80000000000000000000000080000000
PUBLIC	__xmm@80000000000000008000000000000000
PUBLIC	__xmm@80000000800000000000000000000000
EXTRN	_fltused:DWORD
;	COMDAT pdata
pdata	SEGMENT
$pdata$cg_hamilton DD imagerel $LN39
	DD	imagerel $LN39+57
	DD	imagerel $unwind$cg_hamilton
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$cg_hamilton DD imagerel $LN39+57
	DD	imagerel $LN39+475
	DD	imagerel $chain$0$cg_hamilton
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$cg_hamilton DD imagerel $LN39+475
	DD	imagerel $LN39+604
	DD	imagerel $chain$1$cg_hamilton
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$cg_rotate DD imagerel $LN60
	DD	imagerel $LN60+25
	DD	imagerel $unwind$cg_rotate
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$0$cg_rotate DD imagerel $LN60+25
	DD	imagerel $LN60+416
	DD	imagerel $chain$0$cg_rotate
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$1$cg_rotate DD imagerel $LN60+416
	DD	imagerel $LN60+522
	DD	imagerel $chain$1$cg_rotate
pdata	ENDS
;	COMDAT __xmm@80000000800000000000000000000000
CONST	SEGMENT
__xmm@80000000800000000000000000000000 DB 00H, 00H, 00H, 00H, 00H, 00H, 00H
	DB	00H, 00H, 00H, 00H, 080H, 00H, 00H, 00H, 080H
CONST	ENDS
;	COMDAT __xmm@80000000000000008000000000000000
CONST	SEGMENT
__xmm@80000000000000008000000000000000 DB 00H, 00H, 00H, 00H, 00H, 00H, 00H
	DB	080H, 00H, 00H, 00H, 00H, 00H, 00H, 00H, 080H
CONST	ENDS
;	COMDAT __xmm@80000000000000000000000080000000
CONST	SEGMENT
__xmm@80000000000000000000000080000000 DB 00H, 00H, 00H, 080H, 00H, 00H, 00H
	DB	00H, 00H, 00H, 00H, 00H, 00H, 00H, 00H, 080H
CONST	ENDS
;	COMDAT __xmm@40000000400000004000000040000000
CONST	SEGMENT
__xmm@40000000400000004000000040000000 DB 00H, 00H, 00H, '@', 00H, 00H, 00H
	DB	'@', 00H, 00H, 00H, '@', 00H, 00H, 00H, '@'
CONST	ENDS
;	COMDAT __xmm@00000000800000008000000080000000
CONST	SEGMENT
__xmm@00000000800000008000000080000000 DB 00H, 00H, 00H, 080H, 00H, 00H, 00H
	DB	080H, 00H, 00H, 00H, 080H, 00H, 00H, 00H, 00H
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$1$cg_rotate DD 021H
	DD	imagerel $LN60
	DD	imagerel $LN60+25
	DD	imagerel $unwind$cg_rotate
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$cg_rotate DD 020421H
	DD	03404H
	DD	imagerel $LN60
	DD	imagerel $LN60+25
	DD	imagerel $unwind$cg_rotate
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$cg_rotate DD 010401H
	DD	0204H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$1$cg_hamilton DD 021H
	DD	imagerel $LN39
	DD	imagerel $LN39+57
	DD	imagerel $unwind$cg_hamilton
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$chain$0$cg_hamilton DD 020521H
	DD	063405H
	DD	imagerel $LN39
	DD	imagerel $LN39+57
	DD	imagerel $unwind$cg_hamilton
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$cg_hamilton DD 072601H
	DD	08826H
	DD	017819H
	DD	026809H
	DD	06204H
xdata	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?scalar@detail@tnvx@@YA?AT__m128@@M@Z
_TEXT	SEGMENT
value$ = 8
?scalar@detail@tnvx@@YA?AT__m128@@M@Z PROC		; tnvx::detail::scalar, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 58
	shufps	xmm0, xmm0, 0
; Line 59
	ret	0
?scalar@detail@tnvx@@YA?AT__m128@@M@Z ENDP		; tnvx::detail::scalar
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?conjugate@detail@tnvx@@YA?AT__m128@@T3@@Z
_TEXT	SEGMENT
q$ = 8
?conjugate@detail@tnvx@@YA?AT__m128@@T3@@Z PROC		; tnvx::detail::conjugate, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 83
	movdqa	xmm0, XMMWORD PTR __xmm@00000000800000008000000080000000
	xorps	xmm0, XMMWORD PTR [rcx]
; Line 84
	ret	0
?conjugate@detail@tnvx@@YA?AT__m128@@T3@@Z ENDP		; tnvx::detail::conjugate
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?add@detail@tnvx@@YA?AT__m128@@T3@0@Z
_TEXT	SEGMENT
l$ = 8
r$ = 16
?add@detail@tnvx@@YA?AT__m128@@T3@0@Z PROC		; tnvx::detail::add, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 89
	movups	xmm0, XMMWORD PTR [rcx]
	addps	xmm0, XMMWORD PTR [rdx]
; Line 90
	ret	0
?add@detail@tnvx@@YA?AT__m128@@T3@0@Z ENDP		; tnvx::detail::add
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?mul@detail@tnvx@@YA?AT__m128@@T3@0@Z
_TEXT	SEGMENT
l$ = 8
r$ = 16
?mul@detail@tnvx@@YA?AT__m128@@T3@0@Z PROC		; tnvx::detail::mul, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 101
	movups	xmm0, XMMWORD PTR [rcx]
	mulps	xmm0, XMMWORD PTR [rdx]
; Line 102
	ret	0
?mul@detail@tnvx@@YA?AT__m128@@T3@0@Z ENDP		; tnvx::detail::mul
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?dot4@detail@tnvx@@YA?AT__m128@@T3@0@Z
_TEXT	SEGMENT
l$ = 8
r$ = 16
?dot4@detail@tnvx@@YA?AT__m128@@T3@0@Z PROC		; tnvx::detail::dot4, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 125
	movups	xmm0, XMMWORD PTR [rcx]
	mulps	xmm0, XMMWORD PTR [rdx]
; Line 126
	haddps	xmm0, xmm0
; Line 127
	haddps	xmm0, xmm0
; Line 128
	ret	0
?dot4@detail@tnvx@@YA?AT__m128@@T3@0@Z ENDP		; tnvx::detail::dot4
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?magnitude4_sq@detail@tnvx@@YA?AT__m128@@T3@@Z
_TEXT	SEGMENT
v$ = 8
?magnitude4_sq@detail@tnvx@@YA?AT__m128@@T3@@Z PROC	; tnvx::detail::magnitude4_sq, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 151
	movups	xmm0, XMMWORD PTR [rcx]
; Line 125
	mulps	xmm0, xmm0
; Line 126
	haddps	xmm0, xmm0
; Line 127
	haddps	xmm0, xmm0
; Line 152
	ret	0
?magnitude4_sq@detail@tnvx@@YA?AT__m128@@T3@@Z ENDP	; tnvx::detail::magnitude4_sq
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?cross3@detail@tnvx@@YA?AT__m128@@T3@0@Z
_TEXT	SEGMENT
l$ = 8
r$ = 16
?cross3@detail@tnvx@@YA?AT__m128@@T3@0@Z PROC		; tnvx::detail::cross3, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 166
	movups	xmm1, XMMWORD PTR [rdx]
	movups	xmm2, XMMWORD PTR [rcx]
	movaps	xmm0, xmm1
	shufps	xmm0, xmm1, 201				; 000000c9H
	mulps	xmm0, xmm2
	shufps	xmm2, xmm2, 201				; 000000c9H
	mulps	xmm2, xmm1
	subps	xmm0, xmm2
; Line 169
	shufps	xmm0, xmm0, 201				; 000000c9H
; Line 170
	ret	0
?cross3@detail@tnvx@@YA?AT__m128@@T3@0@Z ENDP		; tnvx::detail::cross3
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?quat_mul@detail@tnvx@@YA?AT__m128@@T3@0@Z
_TEXT	SEGMENT
a$ = 8
b$ = 16
?quat_mul@detail@tnvx@@YA?AT__m128@@T3@0@Z PROC		; tnvx::detail::quat_mul, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 249
	movups	xmm3, XMMWORD PTR [rdx]
	movups	xmm4, XMMWORD PTR [rcx]
	movaps	xmm5, xmm3
	movaps	xmm0, xmm4
	shufps	xmm5, xmm3, 177				; 000000b1H
	shufps	xmm0, xmm4, 170				; 000000aaH
	movaps	xmm1, xmm3
; Line 252
	mulps	xmm5, xmm0
	movaps	xmm2, xmm3
	movaps	xmm0, xmm4
	shufps	xmm1, xmm3, 78				; 0000004eH
	shufps	xmm0, xmm4, 85				; 00000055H
	mulps	xmm1, xmm0
	movaps	xmm0, xmm4
	xorps	xmm5, XMMWORD PTR __xmm@80000000000000000000000080000000
	shufps	xmm0, xmm4, 0
	shufps	xmm2, xmm3, 27
	xorps	xmm1, XMMWORD PTR __xmm@80000000800000000000000000000000
	mulps	xmm0, xmm2
; Line 254
	addps	xmm5, xmm1
	shufps	xmm4, xmm4, 255				; 000000ffH
	mulps	xmm4, xmm3
	xorps	xmm0, XMMWORD PTR __xmm@80000000000000008000000000000000
	addps	xmm0, xmm4
	addps	xmm0, xmm5
; Line 255
	ret	0
?quat_mul@detail@tnvx@@YA?AT__m128@@T3@0@Z ENDP		; tnvx::detail::quat_mul
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?rotate@detail@tnvx@@YA?AT__m128@@T3@0@Z
_TEXT	SEGMENT
v$ = 8
q$ = 16
?rotate@detail@tnvx@@YA?AT__m128@@T3@0@Z PROC		; tnvx::detail::rotate, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 261
	movups	xmm5, XMMWORD PTR [rdx]
	movups	xmm4, XMMWORD PTR [rcx]
; Line 163
	movaps	xmm1, xmm5
	shufps	xmm1, xmm5, 201				; 000000c9H
; Line 164
	movaps	xmm3, xmm4
; Line 166
	movaps	xmm0, xmm1
	shufps	xmm3, xmm4, 201				; 000000c9H
	mulps	xmm3, xmm5
	mulps	xmm0, xmm4
	subps	xmm3, xmm0
; Line 169
	shufps	xmm3, xmm3, 201				; 000000c9H
; Line 166
	mulps	xmm1, xmm3
	movaps	xmm2, xmm3
	shufps	xmm2, xmm3, 201				; 000000c9H
	mulps	xmm2, xmm5
; Line 263
	shufps	xmm5, xmm5, 255				; 000000ffH
; Line 166
	subps	xmm2, xmm1
; Line 264
	movdqa	xmm1, XMMWORD PTR __xmm@40000000400000004000000040000000
; Line 101
	mulps	xmm5, xmm1
; Line 169
	shufps	xmm2, xmm2, 201				; 000000c9H
; Line 101
	mulps	xmm5, xmm3
	mulps	xmm2, xmm1
; Line 89
	addps	xmm5, xmm2
	addps	xmm5, xmm4
; Line 267
	movaps	xmm0, xmm5
; Line 268
	ret	0
?rotate@detail@tnvx@@YA?AT__m128@@T3@0@Z ENDP		; tnvx::detail::rotate
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?inverse@detail@tnvx@@YA?AT__m128@@T3@@Z
_TEXT	SEGMENT
q$ = 8
?inverse@detail@tnvx@@YA?AT__m128@@T3@@Z PROC		; tnvx::detail::inverse, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 273
	movups	xmm1, XMMWORD PTR [rcx]
; Line 83
	movdqa	xmm0, XMMWORD PTR __xmm@00000000800000008000000080000000
; Line 125
	movaps	xmm2, xmm1
	mulps	xmm2, xmm1
; Line 83
	xorps	xmm0, xmm1
; Line 126
	haddps	xmm2, xmm2
; Line 127
	haddps	xmm2, xmm2
; Line 273
	divps	xmm0, xmm2
; Line 274
	ret	0
?inverse@detail@tnvx@@YA?AT__m128@@T3@@Z ENDP		; tnvx::detail::inverse
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0Scalar@tnvx@@QEAA@M@Z
_TEXT	SEGMENT
this$ = 8
value$ = 16
??0Scalar@tnvx@@QEAA@M@Z PROC				; tnvx::Scalar::Scalar, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\common\scalar_impl.hpp
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 58
	shufps	xmm1, xmm1, 0
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\common\scalar_impl.hpp
; Line 12
	mov	rax, rcx
	movups	XMMWORD PTR [rcx], xmm1
	ret	0
??0Scalar@tnvx@@QEAA@M@Z ENDP				; tnvx::Scalar::Scalar
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?eval@Scalar@tnvx@@QEBA?AT__m128@@XZ
_TEXT	SEGMENT
this$ = 8
__$ReturnUdt$ = 16
?eval@Scalar@tnvx@@QEBA?AT__m128@@XZ PROC		; tnvx::Scalar::eval, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\common\scalar_impl.hpp
; Line 17
	movups	xmm0, XMMWORD PTR [rcx]
	mov	rax, rdx
	movups	XMMWORD PTR [rdx], xmm0
; Line 18
	ret	0
?eval@Scalar@tnvx@@QEBA?AT__m128@@XZ ENDP		; tnvx::Scalar::eval
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?eval@vec4@tnvx@@QEBA?AT__m128@@XZ
_TEXT	SEGMENT
this$ = 8
__$ReturnUdt$ = 16
?eval@vec4@tnvx@@QEBA?AT__m128@@XZ PROC			; tnvx::vec4::eval, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\vec\vec4_impl.hpp
; Line 17
	movups	xmm0, XMMWORD PTR [rcx]
	mov	rax, rdx
	movups	XMMWORD PTR [rdx], xmm0
; Line 18
	ret	0
?eval@vec4@tnvx@@QEBA?AT__m128@@XZ ENDP			; tnvx::vec4::eval
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?eval@quat@tnvx@@QEBA?AT__m128@@XZ
_TEXT	SEGMENT
this$ = 8
__$ReturnUdt$ = 16
?eval@quat@tnvx@@QEBA?AT__m128@@XZ PROC			; tnvx::quat::eval, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\quat_impl.hpp
; Line 26
	movups	xmm0, XMMWORD PTR [rcx]
	mov	rax, rdx
	movups	XMMWORD PTR [rdx], xmm0
; Line 27
	ret	0
?eval@quat@tnvx@@QEBA?AT__m128@@XZ ENDP			; tnvx::quat::eval
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT cg_hamilton
_TEXT	SEGMENT
qa$ = 64
qb$ = 72
out$ = 80
n$ = 88
cg_hamilton PROC					; COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_quat.cpp
; Line 15
$LN39:
	sub	rsp, 56					; 00000038H
	movaps	XMMWORD PTR [rsp+32], xmm6
	xor	r10d, r10d
; Line 16
	movdqa	xmm6, XMMWORD PTR __xmm@80000000000000008000000000000000
	movaps	XMMWORD PTR [rsp+16], xmm7
	movdqa	xmm7, XMMWORD PTR __xmm@80000000800000000000000000000000
	movaps	XMMWORD PTR [rsp], xmm8
	movdqa	xmm8, XMMWORD PTR __xmm@80000000000000000000000080000000
	cmp	r9, 4
	jb	$LC29@cg_hamilto
	mov	QWORD PTR [rsp+48], rbx
	xor	r11d, r11d
	lea	rbx, QWORD PTR [r9-3]
	npad	11
$LL30@cg_hamilto:
; Line 17
	mov	rax, r10
	add	rax, rax
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\quat_mul_impl.hpp
; Line 11
	movups	xmm3, XMMWORD PTR [rcx+rax*8]
	movups	xmm4, XMMWORD PTR [rdx+rax*8]
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 237
	movaps	xmm0, xmm3
	shufps	xmm0, xmm3, 0
; Line 241
	movaps	xmm2, xmm4
	shufps	xmm2, xmm4, 27
	movaps	xmm1, xmm3
; Line 250
	mulps	xmm2, xmm0
	movaps	xmm0, xmm3
	shufps	xmm1, xmm3, 255				; 000000ffH
	mulps	xmm1, xmm4
	shufps	xmm0, xmm3, 85				; 00000055H
	xorps	xmm2, xmm6
	shufps	xmm3, xmm3, 170				; 000000aaH
; Line 254
	addps	xmm2, xmm1
	movaps	xmm1, xmm4
	shufps	xmm1, xmm4, 78				; 0000004eH
	mulps	xmm1, xmm0
	shufps	xmm4, xmm4, 177				; 000000b1H
	mulps	xmm4, xmm3
	xorps	xmm1, xmm7
	xorps	xmm4, xmm8
	addps	xmm4, xmm1
	addps	xmm4, xmm2
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_quat.cpp
; Line 17
	movups	XMMWORD PTR [r8+rax*8], xmm4
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\quat_mul_impl.hpp
; Line 11
	movups	xmm3, XMMWORD PTR [rdx+rax*8+16]
	movups	xmm4, XMMWORD PTR [rcx+rax*8+16]
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 243
	movaps	xmm5, xmm3
	movaps	xmm0, xmm4
	shufps	xmm5, xmm3, 177				; 000000b1H
	shufps	xmm0, xmm4, 170				; 000000aaH
	movaps	xmm1, xmm3
; Line 252
	mulps	xmm5, xmm0
	movaps	xmm2, xmm3
	shufps	xmm1, xmm3, 78				; 0000004eH
	movaps	xmm0, xmm4
	shufps	xmm0, xmm4, 85				; 00000055H
	mulps	xmm1, xmm0
	movaps	xmm0, xmm4
	shufps	xmm0, xmm4, 0
	xorps	xmm5, xmm8
	shufps	xmm2, xmm3, 27
	mulps	xmm2, xmm0
	shufps	xmm4, xmm4, 255				; 000000ffH
	xorps	xmm1, xmm7
	mulps	xmm4, xmm3
; Line 254
	addps	xmm5, xmm1
	xorps	xmm2, xmm6
	addps	xmm2, xmm4
	addps	xmm5, xmm2
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_quat.cpp
; Line 17
	movups	XMMWORD PTR [r8+rax*8+16], xmm5
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\quat_mul_impl.hpp
; Line 11
	movups	xmm3, XMMWORD PTR [r11+rcx+32]
	movups	xmm4, XMMWORD PTR [r11+rdx+32]
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 237
	movaps	xmm0, xmm3
; Line 241
	movaps	xmm2, xmm4
	shufps	xmm0, xmm3, 0
	shufps	xmm2, xmm4, 27
	movaps	xmm1, xmm3
	shufps	xmm1, xmm3, 255				; 000000ffH
; Line 249
	mulps	xmm1, xmm4
; Line 250
	mulps	xmm2, xmm0
	movaps	xmm0, xmm3
	shufps	xmm0, xmm3, 85				; 00000055H
	shufps	xmm3, xmm3, 170				; 000000aaH
	xorps	xmm2, xmm6
; Line 254
	addps	xmm2, xmm1
	movaps	xmm1, xmm4
	shufps	xmm1, xmm4, 78				; 0000004eH
	shufps	xmm4, xmm4, 177				; 000000b1H
	mulps	xmm4, xmm3
	mulps	xmm1, xmm0
	xorps	xmm4, xmm8
	xorps	xmm1, xmm7
	addps	xmm4, xmm1
	addps	xmm4, xmm2
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_quat.cpp
; Line 17
	movups	XMMWORD PTR [r11+r8+32], xmm4
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\quat_mul_impl.hpp
; Line 11
	movups	xmm3, XMMWORD PTR [r11+rdx+48]
	movups	xmm4, XMMWORD PTR [r11+rcx+48]
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 243
	movaps	xmm5, xmm3
	shufps	xmm5, xmm3, 177				; 000000b1H
	movaps	xmm0, xmm4
	shufps	xmm0, xmm4, 170				; 000000aaH
	movaps	xmm1, xmm3
; Line 252
	mulps	xmm5, xmm0
	movaps	xmm2, xmm3
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_quat.cpp
; Line 17
	add	r10, 4
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 238
	movaps	xmm0, xmm4
; Line 241
	shufps	xmm2, xmm3, 27
	shufps	xmm0, xmm4, 85				; 00000055H
; Line 242
	shufps	xmm1, xmm3, 78				; 0000004eH
; Line 251
	mulps	xmm1, xmm0
; Line 252
	xorps	xmm5, xmm8
	movaps	xmm0, xmm4
	shufps	xmm0, xmm4, 0
	mulps	xmm2, xmm0
	shufps	xmm4, xmm4, 255				; 000000ffH
	xorps	xmm1, xmm7
	mulps	xmm4, xmm3
; Line 254
	addps	xmm5, xmm1
	xorps	xmm2, xmm6
	addps	xmm2, xmm4
	addps	xmm5, xmm2
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_quat.cpp
; Line 17
	movups	XMMWORD PTR [r11+r8+48], xmm5
	add	r11, 64					; 00000040H
	cmp	r10, rbx
	jb	$LL30@cg_hamilto
	mov	rbx, QWORD PTR [rsp+48]
$LC29@cg_hamilto:
; Line 16
	cmp	r10, r9
	jae	SHORT $LN28@cg_hamilto
$LC4@cg_hamilto:
; Line 17
	mov	rax, r10
	inc	r10
	add	rax, rax
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\quat_mul_impl.hpp
; Line 11
	movups	xmm4, XMMWORD PTR [rcx+rax*8]
	movups	xmm3, XMMWORD PTR [rdx+rax*8]
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 239
	movaps	xmm0, xmm4
	shufps	xmm0, xmm4, 170				; 000000aaH
; Line 243
	movaps	xmm5, xmm3
	shufps	xmm5, xmm3, 177				; 000000b1H
	movaps	xmm1, xmm3
; Line 252
	mulps	xmm5, xmm0
	movaps	xmm0, xmm4
	shufps	xmm0, xmm4, 85				; 00000055H
	movaps	xmm2, xmm3
	shufps	xmm2, xmm3, 27
	shufps	xmm1, xmm3, 78				; 0000004eH
	mulps	xmm1, xmm0
	movaps	xmm0, xmm4
	shufps	xmm0, xmm4, 0
	xorps	xmm5, xmm8
	mulps	xmm2, xmm0
	shufps	xmm4, xmm4, 255				; 000000ffH
	xorps	xmm1, xmm7
	mulps	xmm4, xmm3
; Line 254
	addps	xmm5, xmm1
	xorps	xmm2, xmm6
	addps	xmm2, xmm4
	addps	xmm5, xmm2
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_quat.cpp
; Line 17
	movups	XMMWORD PTR [r8+rax*8], xmm5
	cmp	r10, r9
	jb	SHORT $LC4@cg_hamilto
$LN28@cg_hamilto:
; Line 18
	movaps	xmm6, XMMWORD PTR [rsp+32]
	movaps	xmm7, XMMWORD PTR [rsp+16]
	movaps	xmm8, XMMWORD PTR [rsp]
	add	rsp, 56					; 00000038H
	ret	0
cg_hamilton ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?DUquat@tnvx@@U01@@tnvx@@YA?AU?$QuatMul@Uquat@tnvx@@U12@@0@AEBUquat@0@0@Z
_TEXT	SEGMENT
__$ReturnUdt$ = 8
l$ = 16
r$ = 24
??$?DUquat@tnvx@@U01@@tnvx@@YA?AU?$QuatMul@Uquat@tnvx@@U12@@0@AEBUquat@0@0@Z PROC ; tnvx::operator*<tnvx::quat,tnvx::quat>, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\quat_mul_impl.hpp
; Line 11
	movaps	xmm0, XMMWORD PTR [rdx]
; Line 26
	mov	rax, rcx
; Line 11
	movaps	xmm1, XMMWORD PTR [r8]
	movups	XMMWORD PTR [rcx], xmm0
	movups	XMMWORD PTR [rcx+16], xmm1
; Line 27
	ret	0
??$?DUquat@tnvx@@U01@@tnvx@@YA?AU?$QuatMul@Uquat@tnvx@@U12@@0@AEBUquat@0@0@Z ENDP ; tnvx::operator*<tnvx::quat,tnvx::quat>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0?$QuatMul@Uquat@tnvx@@U12@@tnvx@@QEAA@AEIBUquat@1@0@Z
_TEXT	SEGMENT
this$ = 8
l$ = 16
r$ = 24
??0?$QuatMul@Uquat@tnvx@@U12@@tnvx@@QEAA@AEIBUquat@1@0@Z PROC ; tnvx::QuatMul<tnvx::quat,tnvx::quat>::QuatMul<tnvx::quat,tnvx::quat>, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\quat_mul_impl.hpp
; Line 11
	movaps	xmm0, XMMWORD PTR [rdx]
; Line 13
	mov	rax, rcx
	movaps	xmm1, XMMWORD PTR [r8]
	movups	XMMWORD PTR [rcx], xmm0
	movups	XMMWORD PTR [rcx+16], xmm1
	ret	0
??0?$QuatMul@Uquat@tnvx@@U12@@tnvx@@QEAA@AEIBUquat@1@0@Z ENDP ; tnvx::QuatMul<tnvx::quat,tnvx::quat>::QuatMul<tnvx::quat,tnvx::quat>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?eval@?$QuatMul@Uquat@tnvx@@U12@@tnvx@@QEBA?AT__m128@@XZ
_TEXT	SEGMENT
this$ = 8
__$ReturnUdt$ = 16
?eval@?$QuatMul@Uquat@tnvx@@U12@@tnvx@@QEBA?AT__m128@@XZ PROC ; tnvx::QuatMul<tnvx::quat,tnvx::quat>::eval, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\quat_mul_impl.hpp
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\quat_impl.hpp
; Line 26
	movups	xmm3, XMMWORD PTR [rcx+16]
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\quat_mul_impl.hpp
; Line 19
	mov	rax, rdx
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\quat_impl.hpp
; Line 26
	movups	xmm4, XMMWORD PTR [rcx]
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 243
	movaps	xmm5, xmm3
	shufps	xmm5, xmm3, 177				; 000000b1H
	movaps	xmm0, xmm4
	shufps	xmm0, xmm4, 170				; 000000aaH
	movaps	xmm1, xmm3
; Line 252
	mulps	xmm5, xmm0
	movaps	xmm2, xmm3
	movaps	xmm0, xmm4
	shufps	xmm2, xmm3, 27
	shufps	xmm0, xmm4, 85				; 00000055H
	shufps	xmm1, xmm3, 78				; 0000004eH
	xorps	xmm5, XMMWORD PTR __xmm@80000000000000000000000080000000
	mulps	xmm1, xmm0
	movaps	xmm0, xmm4
	shufps	xmm0, xmm4, 0
	mulps	xmm2, xmm0
	xorps	xmm1, XMMWORD PTR __xmm@80000000800000000000000000000000
	shufps	xmm4, xmm4, 255				; 000000ffH
; Line 254
	addps	xmm5, xmm1
	mulps	xmm4, xmm3
	xorps	xmm2, XMMWORD PTR __xmm@80000000000000008000000000000000
	addps	xmm2, xmm4
	addps	xmm5, xmm2
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\quat_mul_impl.hpp
; Line 19
	movups	XMMWORD PTR [rdx], xmm5
; Line 20
	ret	0
?eval@?$QuatMul@Uquat@tnvx@@U12@@tnvx@@QEBA?AT__m128@@XZ ENDP ; tnvx::QuatMul<tnvx::quat,tnvx::quat>::eval
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT cg_rotate
_TEXT	SEGMENT
va$ = 16
qa$ = 24
out$ = 32
n$ = 40
cg_rotate PROC						; COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_quat.cpp
; Line 22
$LN60:
	sub	rsp, 8
; Line 23
	movdqa	xmm5, XMMWORD PTR __xmm@40000000400000004000000040000000
	xor	r10d, r10d
	cmp	r9, 4
	jb	$LC50@cg_rotate
	mov	QWORD PTR [rsp], rbx
	xor	r11d, r11d
	lea	rbx, QWORD PTR [r9-3]
	npad	12
$LL51@cg_rotate:
; Line 24
	mov	rax, r10
	add	rax, rax
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\rotate_impl.hpp
; Line 12
	movups	xmm3, XMMWORD PTR [rdx+rax*8]
	movups	xmm4, XMMWORD PTR [rcx+rax*8]
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 163
	movaps	xmm1, xmm3
	shufps	xmm1, xmm3, 201				; 000000c9H
; Line 164
	movaps	xmm2, xmm4
	shufps	xmm2, xmm4, 201				; 000000c9H
; Line 166
	movaps	xmm0, xmm1
	mulps	xmm2, xmm3
	mulps	xmm0, xmm4
	subps	xmm2, xmm0
; Line 169
	shufps	xmm2, xmm2, 201				; 000000c9H
; Line 166
	mulps	xmm1, xmm2
	movaps	xmm0, xmm2
	shufps	xmm0, xmm2, 201				; 000000c9H
	mulps	xmm0, xmm3
; Line 263
	shufps	xmm3, xmm3, 255				; 000000ffH
; Line 101
	mulps	xmm3, xmm5
; Line 166
	subps	xmm0, xmm1
; Line 101
	mulps	xmm3, xmm2
; Line 169
	shufps	xmm0, xmm0, 201				; 000000c9H
; Line 101
	mulps	xmm0, xmm5
; Line 89
	addps	xmm3, xmm0
	addps	xmm3, xmm4
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_quat.cpp
; Line 24
	movups	XMMWORD PTR [r8+rax*8], xmm3
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\rotate_impl.hpp
; Line 12
	movups	xmm3, XMMWORD PTR [rdx+rax*8+16]
	movups	xmm4, XMMWORD PTR [rcx+rax*8+16]
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 163
	movaps	xmm1, xmm3
	shufps	xmm1, xmm3, 201				; 000000c9H
; Line 164
	movaps	xmm2, xmm4
	shufps	xmm2, xmm4, 201				; 000000c9H
; Line 166
	movaps	xmm0, xmm1
	mulps	xmm2, xmm3
	mulps	xmm0, xmm4
	subps	xmm2, xmm0
; Line 169
	shufps	xmm2, xmm2, 201				; 000000c9H
; Line 166
	mulps	xmm1, xmm2
	movaps	xmm0, xmm2
	shufps	xmm0, xmm2, 201				; 000000c9H
	mulps	xmm0, xmm3
; Line 263
	shufps	xmm3, xmm3, 255				; 000000ffH
; Line 101
	mulps	xmm3, xmm5
; Line 166
	subps	xmm0, xmm1
; Line 101
	mulps	xmm3, xmm2
; Line 169
	shufps	xmm0, xmm0, 201				; 000000c9H
; Line 101
	mulps	xmm0, xmm5
; Line 89
	addps	xmm3, xmm0
	addps	xmm3, xmm4
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_quat.cpp
; Line 24
	movups	XMMWORD PTR [r8+rax*8+16], xmm3
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\rotate_impl.hpp
; Line 12
	movups	xmm3, XMMWORD PTR [r11+rdx+32]
	movups	xmm4, XMMWORD PTR [r11+rcx+32]
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 163
	movaps	xmm1, xmm3
	shufps	xmm1, xmm3, 201				; 000000c9H
; Line 164
	movaps	xmm2, xmm4
	shufps	xmm2, xmm4, 201				; 000000c9H
; Line 166
	movaps	xmm0, xmm1
	mulps	xmm2, xmm3
	mulps	xmm0, xmm4
	subps	xmm2, xmm0
; Line 169
	shufps	xmm2, xmm2, 201				; 000000c9H
; Line 166
	mulps	xmm1, xmm2
	movaps	xmm0, xmm2
	shufps	xmm0, xmm2, 201				; 000000c9H
	mulps	xmm0, xmm3
; Line 263
	shufps	xmm3, xmm3, 255				; 000000ffH
; Line 101
	mulps	xmm3, xmm5
; Line 166
	subps	xmm0, xmm1
; Line 101
	mulps	xmm3, xmm2
; Line 169
	shufps	xmm0, xmm0, 201				; 000000c9H
; Line 101
	mulps	xmm0, xmm5
; Line 89
	addps	xmm3, xmm0
	addps	xmm3, xmm4
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_quat.cpp
; Line 24
	movups	XMMWORD PTR [r11+r8+32], xmm3
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\rotate_impl.hpp
; Line 12
	movups	xmm3, XMMWORD PTR [r11+rdx+48]
	movups	xmm4, XMMWORD PTR [r11+rcx+48]
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 163
	movaps	xmm1, xmm3
; Line 164
	movaps	xmm2, xmm4
	shufps	xmm1, xmm3, 201				; 000000c9H
	shufps	xmm2, xmm4, 201				; 000000c9H
; Line 166
	mulps	xmm2, xmm3
	movaps	xmm0, xmm1
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_quat.cpp
; Line 24
	add	r10, 4
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 166
	mulps	xmm0, xmm4
	subps	xmm2, xmm0
; Line 169
	shufps	xmm2, xmm2, 201				; 000000c9H
; Line 164
	movaps	xmm0, xmm2
; Line 166
	mulps	xmm1, xmm2
	shufps	xmm0, xmm2, 201				; 000000c9H
	mulps	xmm0, xmm3
; Line 263
	shufps	xmm3, xmm3, 255				; 000000ffH
; Line 101
	mulps	xmm3, xmm5
; Line 166
	subps	xmm0, xmm1
; Line 101
	mulps	xmm3, xmm2
; Line 169
	shufps	xmm0, xmm0, 201				; 000000c9H
; Line 101
	mulps	xmm0, xmm5
; Line 89
	addps	xmm3, xmm0
	addps	xmm3, xmm4
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_quat.cpp
; Line 24
	movups	XMMWORD PTR [r11+r8+48], xmm3
	add	r11, 64					; 00000040H
	cmp	r10, rbx
	jb	$LL51@cg_rotate
	mov	rbx, QWORD PTR [rsp]
$LC50@cg_rotate:
; Line 23
	cmp	r10, r9
	jae	SHORT $LN49@cg_rotate
$LC4@cg_rotate:
; Line 24
	mov	rax, r10
	inc	r10
	add	rax, rax
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\rotate_impl.hpp
; Line 12
	movups	xmm4, XMMWORD PTR [rdx+rax*8]
	movups	xmm3, XMMWORD PTR [rcx+rax*8]
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 163
	movaps	xmm1, xmm4
	shufps	xmm1, xmm4, 201				; 000000c9H
; Line 164
	movaps	xmm2, xmm3
	shufps	xmm2, xmm3, 201				; 000000c9H
; Line 166
	movaps	xmm0, xmm1
	mulps	xmm0, xmm3
	mulps	xmm2, xmm4
	subps	xmm2, xmm0
; Line 169
	shufps	xmm2, xmm2, 201				; 000000c9H
; Line 166
	mulps	xmm1, xmm2
	movaps	xmm0, xmm2
	shufps	xmm0, xmm2, 201				; 000000c9H
	mulps	xmm0, xmm4
; Line 263
	shufps	xmm4, xmm4, 255				; 000000ffH
; Line 101
	mulps	xmm4, xmm5
; Line 166
	subps	xmm0, xmm1
; Line 101
	mulps	xmm4, xmm2
; Line 169
	shufps	xmm0, xmm0, 201				; 000000c9H
; Line 101
	mulps	xmm0, xmm5
; Line 89
	addps	xmm4, xmm0
	addps	xmm4, xmm3
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_quat.cpp
; Line 24
	movups	XMMWORD PTR [r8+rax*8], xmm4
	cmp	r10, r9
	jb	SHORT $LC4@cg_rotate
$LN49@cg_rotate:
; Line 25
	add	rsp, 8
	ret	0
cg_rotate ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$rotate@Uvec4@tnvx@@Uquat@2@@tnvx@@YA?AU?$Rotate@Uvec4@tnvx@@Uquat@2@@0@AEBUvec4@0@AEBUquat@0@@Z
_TEXT	SEGMENT
__$ReturnUdt$ = 8
v$ = 16
q$ = 24
??$rotate@Uvec4@tnvx@@Uquat@2@@tnvx@@YA?AU?$Rotate@Uvec4@tnvx@@Uquat@2@@0@AEBUvec4@0@AEBUquat@0@@Z PROC ; tnvx::rotate<tnvx::vec4,tnvx::quat>, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\rotate_impl.hpp
; Line 11
	movaps	xmm0, XMMWORD PTR [rdx]
; Line 26
	mov	rax, rcx
; Line 12
	movaps	xmm1, XMMWORD PTR [r8]
	movups	XMMWORD PTR [rcx], xmm0
	movups	XMMWORD PTR [rcx+16], xmm1
; Line 27
	ret	0
??$rotate@Uvec4@tnvx@@Uquat@2@@tnvx@@YA?AU?$Rotate@Uvec4@tnvx@@Uquat@2@@0@AEBUvec4@0@AEBUquat@0@@Z ENDP ; tnvx::rotate<tnvx::vec4,tnvx::quat>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0?$Rotate@Uvec4@tnvx@@Uquat@2@@tnvx@@QEAA@AEIBUvec4@1@AEIBUquat@1@@Z
_TEXT	SEGMENT
this$ = 8
v$ = 16
q$ = 24
??0?$Rotate@Uvec4@tnvx@@Uquat@2@@tnvx@@QEAA@AEIBUvec4@1@AEIBUquat@1@@Z PROC ; tnvx::Rotate<tnvx::vec4,tnvx::quat>::Rotate<tnvx::vec4,tnvx::quat>, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\rotate_impl.hpp
; Line 11
	movaps	xmm0, XMMWORD PTR [rdx]
; Line 14
	mov	rax, rcx
	movaps	xmm1, XMMWORD PTR [r8]
	movups	XMMWORD PTR [rcx], xmm0
	movups	XMMWORD PTR [rcx+16], xmm1
	ret	0
??0?$Rotate@Uvec4@tnvx@@Uquat@2@@tnvx@@QEAA@AEIBUvec4@1@AEIBUquat@1@@Z ENDP ; tnvx::Rotate<tnvx::vec4,tnvx::quat>::Rotate<tnvx::vec4,tnvx::quat>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?eval@?$Rotate@Uvec4@tnvx@@Uquat@2@@tnvx@@QEBA?AT__m128@@XZ
_TEXT	SEGMENT
this$ = 8
__$ReturnUdt$ = 16
?eval@?$Rotate@Uvec4@tnvx@@Uquat@2@@tnvx@@QEBA?AT__m128@@XZ PROC ; tnvx::Rotate<tnvx::vec4,tnvx::quat>::eval, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\rotate_impl.hpp
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\quat_impl.hpp
; Line 26
	movups	xmm5, XMMWORD PTR [rcx+16]
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\rotate_impl.hpp
; Line 20
	mov	rax, rdx
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\vec\vec4_impl.hpp
; Line 17
	movups	xmm4, XMMWORD PTR [rcx]
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 163
	movaps	xmm1, xmm5
	shufps	xmm1, xmm5, 201				; 000000c9H
; Line 164
	movaps	xmm3, xmm4
	shufps	xmm3, xmm4, 201				; 000000c9H
; Line 166
	movaps	xmm0, xmm1
	mulps	xmm3, xmm5
	mulps	xmm0, xmm4
	subps	xmm3, xmm0
; Line 264
	movdqa	xmm0, XMMWORD PTR __xmm@40000000400000004000000040000000
; Line 169
	shufps	xmm3, xmm3, 201				; 000000c9H
; Line 164
	movaps	xmm2, xmm3
; Line 166
	mulps	xmm1, xmm3
	shufps	xmm2, xmm3, 201				; 000000c9H
	mulps	xmm2, xmm5
; Line 263
	shufps	xmm5, xmm5, 255				; 000000ffH
; Line 101
	mulps	xmm5, xmm0
; Line 166
	subps	xmm2, xmm1
; Line 101
	mulps	xmm5, xmm3
; Line 169
	shufps	xmm2, xmm2, 201				; 000000c9H
; Line 101
	mulps	xmm2, xmm0
; Line 89
	addps	xmm5, xmm2
	addps	xmm5, xmm4
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\rotate_impl.hpp
; Line 20
	movups	XMMWORD PTR [rdx], xmm5
; Line 21
	ret	0
?eval@?$Rotate@Uvec4@tnvx@@Uquat@2@@tnvx@@QEBA?AT__m128@@XZ ENDP ; tnvx::Rotate<tnvx::vec4,tnvx::quat>::eval
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT cg_conj_scale
_TEXT	SEGMENT
qa$ = 8
out$ = 16
n$ = 24
cg_conj_scale PROC					; COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_quat.cpp
; Line 29
	movdqa	xmm1, XMMWORD PTR __xmm@00000000800000008000000080000000
	xor	r9d, r9d
	movdqa	xmm2, XMMWORD PTR __xmm@40000000400000004000000040000000
	cmp	r8, 4
	jb	SHORT $LC47@cg_conj_sc
	lea	r11, QWORD PTR [r8-3]
	xor	r10d, r10d
$LL48@cg_conj_sc:
; Line 30
	mov	rax, r9
	lea	r10, QWORD PTR [r10+64]
	add	rax, rax
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 83
	movaps	xmm0, xmm1
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_quat.cpp
; Line 30
	add	r9, 4
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 83
	xorps	xmm0, XMMWORD PTR [rcx+rax*8]
; Line 101
	mulps	xmm0, xmm2
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_quat.cpp
; Line 30
	movups	XMMWORD PTR [rdx+rax*8], xmm0
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 83
	movaps	xmm0, xmm1
	xorps	xmm0, XMMWORD PTR [rcx+rax*8+16]
; Line 101
	mulps	xmm0, xmm2
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_quat.cpp
; Line 30
	movups	XMMWORD PTR [rdx+rax*8+16], xmm0
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 83
	movaps	xmm0, xmm1
	xorps	xmm0, XMMWORD PTR [r10+rcx-32]
; Line 101
	mulps	xmm0, xmm2
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_quat.cpp
; Line 30
	movups	XMMWORD PTR [r10+rdx-32], xmm0
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 83
	movaps	xmm0, xmm1
	xorps	xmm0, XMMWORD PTR [r10+rcx-16]
; Line 101
	mulps	xmm0, xmm2
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_quat.cpp
; Line 30
	movups	XMMWORD PTR [r10+rdx-16], xmm0
	cmp	r9, r11
	jb	SHORT $LL48@cg_conj_sc
$LC47@cg_conj_sc:
; Line 29
	cmp	r9, r8
	jae	SHORT $LN46@cg_conj_sc
$LC4@cg_conj_sc:
; Line 30
	mov	rax, r9
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 83
	movaps	xmm0, xmm1
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_quat.cpp
; Line 30
	add	rax, rax
	inc	r9
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 83
	xorps	xmm0, XMMWORD PTR [rcx+rax*8]
; Line 101
	mulps	xmm0, xmm2
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_quat.cpp
; Line 30
	movups	XMMWORD PTR [rdx+rax*8], xmm0
	cmp	r9, r8
	jb	SHORT $LC4@cg_conj_sc
$LN46@cg_conj_sc:
; Line 31
	ret	0
cg_conj_scale ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$conjugate@Uquat@tnvx@@@tnvx@@YA?AU?$Conjugate@Uquat@tnvx@@@0@AEBUquat@0@@Z
_TEXT	SEGMENT
__$ReturnUdt$ = 8
q$ = 16
??$conjugate@Uquat@tnvx@@@tnvx@@YA?AU?$Conjugate@Uquat@tnvx@@@0@AEBUquat@0@@Z PROC ; tnvx::conjugate<tnvx::quat>, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\conjugate_impl.hpp
; Line 11
	movaps	xmm0, XMMWORD PTR [rdx]
; Line 26
	mov	rax, rcx
; Line 11
	movups	XMMWORD PTR [rcx], xmm0
; Line 27
	ret	0
??$conjugate@Uquat@tnvx@@@tnvx@@YA?AU?$Conjugate@Uquat@tnvx@@@0@AEBUquat@0@@Z ENDP ; tnvx::conjugate<tnvx::quat>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0?$Conjugate@Uquat@tnvx@@@tnvx@@QEAA@AEIBUquat@1@@Z
_TEXT	SEGMENT
this$ = 8
expr$ = 16
??0?$Conjugate@Uquat@tnvx@@@tnvx@@QEAA@AEIBUquat@1@@Z PROC ; tnvx::Conjugate<tnvx::quat>::Conjugate<tnvx::quat>, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\conjugate_impl.hpp
; Line 11
	movaps	xmm0, XMMWORD PTR [rdx]
; Line 13
	mov	rax, rcx
	movups	XMMWORD PTR [rcx], xmm0
	ret	0
??0?$Conjugate@Uquat@tnvx@@@tnvx@@QEAA@AEIBUquat@1@@Z ENDP ; tnvx::Conjugate<tnvx::quat>::Conjugate<tnvx::quat>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?eval@?$Conjugate@Uquat@tnvx@@@tnvx@@QEBA?AT__m128@@XZ
_TEXT	SEGMENT
this$ = 8
__$ReturnUdt$ = 16
?eval@?$Conjugate@Uquat@tnvx@@@tnvx@@QEBA?AT__m128@@XZ PROC ; tnvx::Conjugate<tnvx::quat>::eval, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\conjugate_impl.hpp
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 83
	movdqa	xmm0, XMMWORD PTR __xmm@00000000800000008000000080000000
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\conjugate_impl.hpp
; Line 19
	mov	rax, rdx
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 83
	xorps	xmm0, XMMWORD PTR [rcx]
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\conjugate_impl.hpp
; Line 19
	movups	XMMWORD PTR [rdx], xmm0
; Line 20
	ret	0
?eval@?$Conjugate@Uquat@tnvx@@@tnvx@@QEBA?AT__m128@@XZ ENDP ; tnvx::Conjugate<tnvx::quat>::eval
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$?DU?$Conjugate@Uquat@tnvx@@@tnvx@@@tnvx@@YA?AU?$Mul@U?$Conjugate@Uquat@tnvx@@@tnvx@@UScalar@2@@0@AEBU?$Conjugate@Uquat@tnvx@@@0@M@Z
_TEXT	SEGMENT
__$ReturnUdt$ = 8
l$ = 16
r$ = 24
??$?DU?$Conjugate@Uquat@tnvx@@@tnvx@@@tnvx@@YA?AU?$Mul@U?$Conjugate@Uquat@tnvx@@@tnvx@@UScalar@2@@0@AEBU?$Conjugate@Uquat@tnvx@@@0@M@Z PROC ; tnvx::operator*<tnvx::Conjugate<tnvx::quat> >, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\common\mul_impl.hpp
; Line 12
	movups	xmm0, XMMWORD PTR [rdx]
; Line 85
	mov	rax, rcx
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 58
	shufps	xmm2, xmm2, 0
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\common\mul_impl.hpp
; Line 12
	movups	XMMWORD PTR [rcx], xmm0
; Line 13
	movups	XMMWORD PTR [rcx+16], xmm2
; Line 86
	ret	0
??$?DU?$Conjugate@Uquat@tnvx@@@tnvx@@@tnvx@@YA?AU?$Mul@U?$Conjugate@Uquat@tnvx@@@tnvx@@UScalar@2@@0@AEBU?$Conjugate@Uquat@tnvx@@@0@M@Z ENDP ; tnvx::operator*<tnvx::Conjugate<tnvx::quat> >
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0?$Mul@U?$Conjugate@Uquat@tnvx@@@tnvx@@UScalar@2@@tnvx@@QEAA@AEIBU?$Conjugate@Uquat@tnvx@@@1@AEIBUScalar@1@@Z
_TEXT	SEGMENT
this$ = 8
l$ = 16
r$ = 24
??0?$Mul@U?$Conjugate@Uquat@tnvx@@@tnvx@@UScalar@2@@tnvx@@QEAA@AEIBU?$Conjugate@Uquat@tnvx@@@1@AEIBUScalar@1@@Z PROC ; tnvx::Mul<tnvx::Conjugate<tnvx::quat>,tnvx::Scalar>::Mul<tnvx::Conjugate<tnvx::quat>,tnvx::Scalar>, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\common\mul_impl.hpp
; Line 12
	movaps	xmm0, XMMWORD PTR [rdx]
; Line 15
	mov	rax, rcx
	movaps	xmm1, XMMWORD PTR [r8]
	movups	XMMWORD PTR [rcx], xmm0
	movups	XMMWORD PTR [rcx+16], xmm1
	ret	0
??0?$Mul@U?$Conjugate@Uquat@tnvx@@@tnvx@@UScalar@2@@tnvx@@QEAA@AEIBU?$Conjugate@Uquat@tnvx@@@1@AEIBUScalar@1@@Z ENDP ; tnvx::Mul<tnvx::Conjugate<tnvx::quat>,tnvx::Scalar>::Mul<tnvx::Conjugate<tnvx::quat>,tnvx::Scalar>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?eval@?$Mul@U?$Conjugate@Uquat@tnvx@@@tnvx@@UScalar@2@@tnvx@@QEBA?AT__m128@@XZ
_TEXT	SEGMENT
this$ = 8
__$ReturnUdt$ = 16
?eval@?$Mul@U?$Conjugate@Uquat@tnvx@@@tnvx@@UScalar@2@@tnvx@@QEBA?AT__m128@@XZ PROC ; tnvx::Mul<tnvx::Conjugate<tnvx::quat>,tnvx::Scalar>::eval, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\common\mul_impl.hpp
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 83
	movdqa	xmm0, XMMWORD PTR __xmm@00000000800000008000000080000000
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\common\mul_impl.hpp
; Line 22
	mov	rax, rdx
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 83
	xorps	xmm0, XMMWORD PTR [rcx]
; Line 101
	mulps	xmm0, XMMWORD PTR [rcx+16]
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\common\mul_impl.hpp
; Line 22
	movups	XMMWORD PTR [rdx], xmm0
; Line 23
	ret	0
?eval@?$Mul@U?$Conjugate@Uquat@tnvx@@@tnvx@@UScalar@2@@tnvx@@QEBA?AT__m128@@XZ ENDP ; tnvx::Mul<tnvx::Conjugate<tnvx::quat>,tnvx::Scalar>::eval
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT cg_quat_inverse
_TEXT	SEGMENT
qa$ = 8
out$ = 16
n$ = 24
cg_quat_inverse PROC					; COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_quat.cpp
; Line 35
	movdqa	xmm3, XMMWORD PTR __xmm@00000000800000008000000080000000
	xor	r9d, r9d
	cmp	r8, 4
	jb	$LC35@cg_quat_in
	lea	r11, QWORD PTR [r8-3]
	xor	r10d, r10d
	npad	4
$LL36@cg_quat_in:
; Line 36
	mov	rax, r9
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 83
	movaps	xmm0, xmm3
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_quat.cpp
; Line 36
	add	rax, rax
	add	r9, 4
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\inverse_impl.hpp
; Line 19
	movups	xmm1, XMMWORD PTR [rcx+rax*8]
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 83
	xorps	xmm0, xmm1
; Line 125
	movaps	xmm2, xmm1
	mulps	xmm2, xmm1
; Line 126
	haddps	xmm2, xmm2
; Line 127
	haddps	xmm2, xmm2
; Line 273
	divps	xmm0, xmm2
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_quat.cpp
; Line 36
	movups	XMMWORD PTR [rdx+rax*8], xmm0
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 83
	movaps	xmm0, xmm3
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\inverse_impl.hpp
; Line 19
	movups	xmm1, XMMWORD PTR [rcx+rax*8+16]
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 83
	xorps	xmm0, xmm1
; Line 125
	movaps	xmm2, xmm1
	mulps	xmm2, xmm1
; Line 126
	haddps	xmm2, xmm2
; Line 127
	haddps	xmm2, xmm2
; Line 273
	divps	xmm0, xmm2
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_quat.cpp
; Line 36
	movups	XMMWORD PTR [rdx+rax*8+16], xmm0
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 83
	movaps	xmm0, xmm3
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\inverse_impl.hpp
; Line 19
	movups	xmm1, XMMWORD PTR [r10+rcx+32]
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 83
	xorps	xmm0, xmm1
; Line 125
	movaps	xmm2, xmm1
	mulps	xmm2, xmm1
; Line 126
	haddps	xmm2, xmm2
; Line 127
	haddps	xmm2, xmm2
; Line 273
	divps	xmm0, xmm2
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_quat.cpp
; Line 36
	movups	XMMWORD PTR [r10+rdx+32], xmm0
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 83
	movaps	xmm0, xmm3
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\inverse_impl.hpp
; Line 19
	movups	xmm1, XMMWORD PTR [r10+rcx+48]
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 125
	movaps	xmm2, xmm1
; Line 83
	xorps	xmm0, xmm1
; Line 125
	mulps	xmm2, xmm1
; Line 126
	haddps	xmm2, xmm2
; Line 127
	haddps	xmm2, xmm2
; Line 273
	divps	xmm0, xmm2
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_quat.cpp
; Line 36
	movups	XMMWORD PTR [r10+rdx+48], xmm0
	add	r10, 64					; 00000040H
	cmp	r9, r11
	jb	$LL36@cg_quat_in
$LC35@cg_quat_in:
; Line 35
	cmp	r9, r8
	jae	SHORT $LN34@cg_quat_in
$LC4@cg_quat_in:
; Line 36
	mov	rax, r9
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 83
	movaps	xmm0, xmm3
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_quat.cpp
; Line 36
	add	rax, rax
	inc	r9
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\inverse_impl.hpp
; Line 19
	movups	xmm1, XMMWORD PTR [rcx+rax*8]
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 125
	movaps	xmm2, xmm1
; Line 83
	xorps	xmm0, xmm1
; Line 125
	mulps	xmm2, xmm1
; Line 126
	haddps	xmm2, xmm2
; Line 127
	haddps	xmm2, xmm2
; Line 273
	divps	xmm0, xmm2
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_quat.cpp
; Line 36
	movups	XMMWORD PTR [rdx+rax*8], xmm0
	cmp	r9, r8
	jb	SHORT $LC4@cg_quat_in
$LN34@cg_quat_in:
; Line 37
	ret	0
cg_quat_inverse ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??$inverse@Uquat@tnvx@@@tnvx@@YA?AU?$Inverse@Uquat@tnvx@@@0@AEBUquat@0@@Z
_TEXT	SEGMENT
__$ReturnUdt$ = 8
e$ = 16
??$inverse@Uquat@tnvx@@@tnvx@@YA?AU?$Inverse@Uquat@tnvx@@@0@AEBUquat@0@@Z PROC ; tnvx::inverse<tnvx::quat>, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\inverse_impl.hpp
; Line 11
	movaps	xmm0, XMMWORD PTR [rdx]
; Line 26
	mov	rax, rcx
; Line 11
	movups	XMMWORD PTR [rcx], xmm0
; Line 27
	ret	0
??$inverse@Uquat@tnvx@@@tnvx@@YA?AU?$Inverse@Uquat@tnvx@@@0@AEBUquat@0@@Z ENDP ; tnvx::inverse<tnvx::quat>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ??0?$Inverse@Uquat@tnvx@@@tnvx@@QEAA@AEIBUquat@1@@Z
_TEXT	SEGMENT
this$ = 8
e$ = 16
??0?$Inverse@Uquat@tnvx@@@tnvx@@QEAA@AEIBUquat@1@@Z PROC ; tnvx::Inverse<tnvx::quat>::Inverse<tnvx::quat>, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\inverse_impl.hpp
; Line 11
	movaps	xmm0, XMMWORD PTR [rdx]
; Line 13
	mov	rax, rcx
	movups	XMMWORD PTR [rcx], xmm0
	ret	0
??0?$Inverse@Uquat@tnvx@@@tnvx@@QEAA@AEIBUquat@1@@Z ENDP ; tnvx::Inverse<tnvx::quat>::Inverse<tnvx::quat>
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?eval@?$Inverse@Uquat@tnvx@@@tnvx@@QEBA?AT__m128@@XZ
_TEXT	SEGMENT
this$ = 8
__$ReturnUdt$ = 16
?eval@?$Inverse@Uquat@tnvx@@@tnvx@@QEBA?AT__m128@@XZ PROC ; tnvx::Inverse<tnvx::quat>::eval, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\inverse_impl.hpp
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\quat_impl.hpp
; Line 26
	movups	xmm1, XMMWORD PTR [rcx]
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\inverse_impl.hpp
; Line 19
	mov	rax, rdx
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 83
	movdqa	xmm0, XMMWORD PTR __xmm@00000000800000008000000080000000
; Line 125
	movaps	xmm2, xmm1
	mulps	xmm2, xmm1
; Line 83
	xorps	xmm0, xmm1
; Line 126
	haddps	xmm2, xmm2
; Line 127
	haddps	xmm2, xmm2
; Line 273
	divps	xmm0, xmm2
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\quat\inverse_impl.hpp
; Line 19
	movups	XMMWORD PTR [rdx], xmm0
; Line 20
	ret	0
?eval@?$Inverse@Uquat@tnvx@@@tnvx@@QEBA?AT__m128@@XZ ENDP ; tnvx::Inverse<tnvx::quat>::eval
_TEXT	ENDS
END
