; Microsoft (R) C/C++ Optimizing Compiler Version 19.51.36248 for x64
; cl /nologo /c /O2 /std:c++20 /EHsc /W3 /Isrc\tenvex /FA cg_reference.cpp
; Listing generated by Microsoft (R) Optimizing Compiler Version 19.51.36248.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?add@detail@tnvx@@YA?AT__m128@@T3@0@Z		; tnvx::detail::add
PUBLIC	?mul@detail@tnvx@@YA?AT__m128@@T3@0@Z		; tnvx::detail::mul
PUBLIC	cg_clean
PUBLIC	cg_spilled
EXTRN	cg_opaque_kernel:PROC
;	COMDAT pdata
pdata	SEGMENT
$pdata$cg_spilled DD imagerel $LN4
	DD	imagerel $LN4+69
	DD	imagerel $unwind$cg_spilled
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$cg_spilled DD 010401H
	DD	0a204H
xdata	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?add@detail@tnvx@@YA?AT__m128@@T3@0@Z
_TEXT	SEGMENT
l$ = 8
r$ = 16
?add@detail@tnvx@@YA?AT__m128@@T3@0@Z PROC		; tnvx::detail::add, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 89
	movups	xmm0, XMMWORD PTR [rcx]
	addps	xmm0, XMMWORD PTR [rdx]
; Line 90
	ret	0
?add@detail@tnvx@@YA?AT__m128@@T3@0@Z ENDP		; tnvx::detail::add
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?mul@detail@tnvx@@YA?AT__m128@@T3@0@Z
_TEXT	SEGMENT
l$ = 8
r$ = 16
?mul@detail@tnvx@@YA?AT__m128@@T3@0@Z PROC		; tnvx::detail::mul, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 101
	movups	xmm0, XMMWORD PTR [rcx]
	mulps	xmm0, XMMWORD PTR [rdx]
; Line 102
	ret	0
?mul@detail@tnvx@@YA?AT__m128@@T3@0@Z ENDP		; tnvx::detail::mul
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?fused_kernel@@YA?AT__m128@@T1@0@Z
_TEXT	SEGMENT
x$ = 8
y$ = 16
?fused_kernel@@YA?AT__m128@@T1@0@Z PROC			; fused_kernel, COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_reference.cpp
; Line 16
	movups	xmm1, XMMWORD PTR [rdx]
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 101
	movaps	xmm0, xmm1
	mulps	xmm0, XMMWORD PTR [rcx]
; Line 89
	addps	xmm0, xmm1
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_reference.cpp
; Line 17
	ret	0
?fused_kernel@@YA?AT__m128@@T1@0@Z ENDP			; fused_kernel
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT cg_clean
_TEXT	SEGMENT
a$ = 8
b$ = 16
c$ = 24
cg_clean PROC						; COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_reference.cpp
; Line 21
	movups	xmm1, XMMWORD PTR [rdx]
	movups	xmm2, XMMWORD PTR [r8]
; File C:\Users\artem.zyktin\projects\tenvex\src\tenvex\expressions\core\core_sse.h
; Line 101
	movaps	xmm0, xmm1
	mulps	xmm0, XMMWORD PTR [rcx]
; Line 89
	addps	xmm0, xmm1
; Line 101
	mulps	xmm0, xmm2
; Line 89
	addps	xmm0, xmm2
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_reference.cpp
; Line 22
	ret	0
cg_clean ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT cg_spilled
_TEXT	SEGMENT
$T1 = 32
$T2 = 48
$T3 = 48
$T4 = 64
a$ = 96
b$ = 104
c$ = 112
cg_spilled PROC						; COMDAT
; File C:\Users\artem.zyktin\projects\tenvex\src\codegen\cg_reference.cpp
; Line 25
$LN4:
	sub	rsp, 88					; 00000058H
; Line 26
	movups	xmm0, XMMWORD PTR [r8]
	movups	xmm1, XMMWORD PTR [rdx]
	lea	rdx, QWORD PTR $T1[rsp]
	movaps	XMMWORD PTR $T4[rsp], xmm0
	movups	xmm0, XMMWORD PTR [rcx]
	lea	rcx, QWORD PTR $T2[rsp]
	movaps	XMMWORD PTR $T2[rsp], xmm0
	movaps	XMMWORD PTR $T1[rsp], xmm1
	call	cg_opaque_kernel
	lea	rdx, QWORD PTR $T4[rsp]
	movaps	XMMWORD PTR $T3[rsp], xmm0
	lea	rcx, QWORD PTR $T3[rsp]
	call	cg_opaque_kernel
; Line 27
	add	rsp, 88					; 00000058H
	ret	0
cg_spilled ENDP
_TEXT	ENDS
END
