#pragma once

#include "vec\abs.h"
#include "vec\ceil.h"
#include "vec\cross3.h"
#include "vec\dot3.h"
#include "vec\floor.h"
#include "vec\frac.h"
#include "vec\hadamard.h"
#include "vec\magnitude3.h"
#include "vec\magnitude3_compare.h"
#include "vec\magnitude3_sq.h"
#include "vec\max.h"
#include "vec\min.h"
#include "vec\round.h"
#include "vec\vec_operations.h"
#include "vec\vec4.h"
#include "vec\with_w.h"
